### ISSUE TITLE
Use TextureEffect as material

### ISSUE THREAD

**Issue by lhamadopagode** [vanruesc/postprocessing#104]
Is there any way to use a TextureEffect as material from an object? 
I need to use blend mode on a texture in a plane, the texture is transparent and need to affect the color of the object behind. 
I tried to look into source code and documentation but did not find anyway to do that by myself. 

Edit: Works for me if i am able to use an BlendMode on a Three.MeshBasicMaterial as well.

Thanks a lot!

**Comment by vanruesc** [comment]
Hi,

the `postprocessing` library is intended for screen space image manipulation. It's not advisable to use its components for common 3D scenes unless you know what you're doing.

The built-in materials from [three](https://threejs.org/) have a [Material.blending](https://threejs.org/docs/#api/en/materials/Material.blending) property that you can set to `CustomBlending`. There's a list of available blend functions in the [CustomBlendingEquation](https://threejs.org/docs/#api/en/constants/CustomBlendingEquations) docs. If that doesn't offer enough flexibility for your use case, I'm afraid you're out of luck.

**Comment by lhamadopagode** [comment]
Yeah, I need overlay and divide blending, thanks for the help!

**Comment by vanruesc** [comment]
Check out the [Refraction](https://threejs.org/examples/?q=refraction#webgl_refraction) implementation from the three.js examples. You could customize the water shader that is used in this example to only implement texture blending.

**Comment by lhamadopagode** [comment]
I'll try that, thanks a lot!
