### ISSUE TITLE
Weird fragmenting with Realistic Bokeh

### ISSUE THREAD

**Issue by deadlocked247** [vanruesc/postprocessing#108]
Hey,
First off this is a great library! Thank you!
I'm trying to use `RealisticBokeh` to add depth to my scene and I'm getting weird fragments like this on an image texture from three
![image](https://user-images.githubusercontent.com/7194264/53389400-2e1e7300-395d-11e9-9868-8284fe428cdb.png)
![image](https://user-images.githubusercontent.com/7194264/53389463-6aea6a00-395d-11e9-9649-16f530f819e1.png)

```
      const composer = new EffectComposer(renderer);

      const smaaEffect = new SMAAEffect(data.searchImage, data.areaImage);

      const renderPass = new RenderPass(scene, camera);
      smaaEffect.setEdgeDetectionThreshold(0.06);

      const bokehEffect = new RealisticBokehEffect({
        focus: 1.55,
        focalLength: 0.5,
        luminanceThreshold: 0.325,
        luminanceGain: 2.0,
        bias: -0.35,
        fringe: 0.7,
        maxBlur: 2.5,
        rings: 6,
        samples: 5,
        showFocus: false,
        manualDoF: false,
        pentagon: true
      });

      const smaaPass = new EffectPass(camera, smaaEffect);
      const bokehPass = new EffectPass(
        camera,
        bokehEffect,
        new VignetteEffect()
      );

      renderPass.renderToScreen = false;
      smaaPass.renderToScreen = true;
      composer.addPass(renderPass);
      composer.addPass(bokehPass);
      composer.addPass(smaaPass);
```

Thanks for your help!

**Comment by vanruesc** [comment]
Hi,

do you get the same artifacts in the [postprocessing demo](http://vanruesc.github.io/postprocessing/public/demo/#realistic-bokeh)? If so, do you also see these artifacts in the [three.js demo](https://threejs.org/examples/?q=dof#webgl_postprocessing_dof2)?

What are your system specs?

**Comment by deadlocked247** [comment]
Thanks for the response!
The demos do not give me the problem. 
I set up a simple codepen to try to recreate it but it didn't help
https://codepen.io/deadlocked247/pen/JzoKmg

Systems specs 
```
Radeon Pro 560X 4096 MB
Intel UHD Graphics 630 1536 M
2.9 GHz Intel Core i9
32 GB 2400 MHz DDR4
```

Do not think that is the problem. I can provide more details about my scene setup if needed.

Thanks for you help!

**Comment by vanruesc** [comment]
> The demos do not give me the problem.

That's good to hear, thanks for testing. There might be something wrong with your scene configuration apart from the code you've already posted. I can't tell from your screenshots what the cause of the artifacts might be, but it seems to be a depth-related issue. The next thing we need is a setup that reproduces the bug.

I've changed a few things in the codepen example: https://codepen.io/anon/pen/GegWjv

Please try to adjust some parameters and add things from your scene setup one-by-one to find out what exactly is causing these artifacts. Pay special attention to your camera settings (`near` and `far`) as well as the `focus` and `focalLength` parameters of the `BokehEffect`.

**Comment by deadlocked247** [comment]
After some further debugging it seems like `FBXLoader` is causing the problems, converted my file to Collada and it worked fine.
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader.js

Probably not something worth fixing in the scope of this project but thought I would mention it anyways, thanks for your help!
