### ISSUE TITLE
Problem with input-output between passes

### ISSUE THREAD

**Issue by dghez** [vanruesc/postprocessing#111]
I was trying to create a simple `ShaderPass` and I was struggling with the `tDiffuse` uniform because it looked it doesn't work. So I tried to create a `EffectPass` with Bloom and Vignette just for testing and the output was correct as the filter but the "content" of the scene was missing, just like the `ShaderPass`. 
I remembered that I created something similar last week so I dig into the code I wrote looking for some errors but it looked everything right to me. 
I tried to copy that code into this new demo and it doesn't work neither.
So I thought it could be a bug or something similar, so I got another version of the package `5.6.0` and without any changes in my code it starts to work again.

**UPDATE:** Looks like that is something wrong with only the objects in the scene, because if I change the clearColor or the renderer `renderer.setClearColor(color)` it displays that color, without any mesh

```
import * as THREE from 'three'
import { EffectComposer, RenderPass, ShaderPass } from 'postprocessing'

import vertexShader from './shaders/toon.vert'
import fragmentShader from './shaders/toon.frag'

export default class Postprocessing {
  constructor (renderer, camera, scene) {
    this.composer = new EffectComposer(renderer)
    this.renderPass = new RenderPass(scene, camera)

    this.composer.addPass(this.renderPass)

    const shaderMaterial = new THREE.ShaderMaterial({
      uniforms: {
        tDiffuse: { type: 't', value: null }
      },
      vertexShader: vertexShader,
      fragmentShader: fragmentShader
    })

    this.shaderPass = new ShaderPass(shaderMaterial, 'tDiffuse')
    this.composer.addPass(this.shaderPass)

    this.shaderPass.renderToScreen = true
  }

  render () {
    this.composer.render()
  }
}

```

This snippet works fine in `5.6.0` and not in `6.0.1`

**RENDERED USING `5.6.0`**
<img width="1439" alt="schermata 2019-03-06 alle 12 47 45" src="https://user-images.githubusercontent.com/6367879/53879314-6f261f80-400e-11e9-8990-c329be03eff7.png">

**RENDERED USING `6.0.1`**
<img width="721" alt="schermata 2019-03-06 alle 12 48 31" src="https://user-images.githubusercontent.com/6367879/53879323-74836a00-400e-11e9-94f0-a5cdca79948f.png">

**Comment by vanruesc** [comment]
Hi dghez,

which version of three are you using? The latest `postprocessing` version doesn't support requires three r102.

**Comment by vanruesc** [comment]
Also, if you're having trouble with the `ShaderPass`, the following example might help you: https://jsfiddle.net/6sctr5yn/

Note that the `ShaderPass` assumes the name of the input buffer uniform to be "inputBuffer" as described in the [documentation](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/ShaderPass.js~ShaderPass.html#instance-constructor-constructor). If the uniform in your `ShaderMaterial` is called "tDiffuse", you'll have to provide that name to the constructor!

**Comment by dghez** [comment]
> ! Nevermind, I didn't notice that you're already doing that in your code 😇

Yeah, I'm quite familiar with this awesome library, I use this for quite a while ;)
Btw, I was using `three r100`, now I upgraded it to `r102` and everything works fine.
My bad I didn't noticed, sorry for the opening issue.

**Comment by vanruesc** [comment]
> My bad I didn't noticed, sorry for the opening issue.

No problem, I'm glad you were able to resolve your issue!
