### ISSUE TITLE
GodRaysEffect cut off when camera not in view of light source POINT

### ISSUE THREAD

**Issue by davidck** [vanruesc/postprocessing#112]
Hi,

Thanks for the library, it's awesome 👍 

Sorry I'm not 100% familiar with the lib let alone THREE.JS...
I followed mostly the demo from here:
https://vanruesc.github.io/postprocessing/public/demo/#god-rays

If I rotate my camera out of view from the light source, I don't see the render anymore.   This doesn't happen in the demo (the tree is still visible when the rays aren't facing the camera).

Here's a screenshot of it working properly:
<img width="964" alt="screen shot 2019-03-06 at 6 08 19 pm" src="https://user-images.githubusercontent.com/135805/53920481-55e79800-403b-11e9-9d86-8452f9a111e5.png">

Here's a screenshot of the cut off when camera partially cuts the light source:
<img width="946" alt="screen shot 2019-03-06 at 6 08 04 pm" src="https://user-images.githubusercontent.com/135805/53920502-6d268580-403b-11e9-8686-26ba9b851bd2.png">

And here's a screenshot when the light source is totally out of view of the camera:
<img width="960" alt="screen shot 2019-03-06 at 6 12 52 pm" src="https://user-images.githubusercontent.com/135805/53920531-84fe0980-403b-11e9-9a0c-80f508d8f947.png">

I tried setting an ambient light + a directional light to no avail.

Is there a clip max setting?

**Comment by vanruesc** [comment]
Hi,

I don't think that the post processing filter is causing this clipping. Please post your scene setup, especially your renderer, effect composer, sky box and camera configuration. Maybe there's a problem with your model; have you tried using any other model in your setup?

If possible, create a minimal test case that reproduces the issue. You can use the following example as a starting point: https://jsfiddle.net/znhspj19/

**Comment by davidck** [comment]
Thanks for the response, I will set up a test.

Some more info:

If I don’t use this effect pass, and just use my rendering pass, it works fine.

I’ve also used another effect pass, the glitch effect and it also works.

Just having trouble with this one.  And I did turn renderToScreen to false on the render pass and the glitch pass.

I also don’t have a skybox not a scene background.  The star field is grouped with the ship and camera so they all move together.

**Comment by davidck** [comment]
Thanks for setting up the starting point js fiddle, that's really cool.
I've made some quick mods:
https://jsfiddle.net/a09sy3nf/5/

I think it makes sense that once the camera loses view of the light source point, the effect disappears.  Looks broken but it seems intentional.   In my version, the torus no longer shows, but in the fiddle, it still works.  I'll keep exploring and will update if I can reproduce it in your fiddle.

Thanks

**Comment by vanruesc** [comment]
> I think it makes sense that once the camera loses view of the light source point, the effect disappears. Looks broken but it seems intentional.

The `GodRaysEffect` renders the light source to a render texture and blurs it along radial lines towards the light center. If the light source is not in view, there will be nothing to blur. There's actually a lot more to it than one might think. The god rays implementation in this library is fairly robust as it prevents the light rays from flipping at certain angles when the light source is not in the frame.

Thanks for your input via the fiddle. I've noticed that you're trying to render your scene at extreme dimensions. The space between your camera's near and far plane is very large. This means that your depth values will be highly inaccurate, which will result in all sorts of funky issues.

There are several solutions to this problem, though. I recommend looking into literature about the linear depth buffer and rendering on a planetary scale. There are special techniques for this. One approach uses multiple camera with different near/far plane settings to render scenes at different distances while keeping the depth values intact. Another technique is to use logarithmic depth. Three.js provides a built-in implementation of this technique. I use this feature all the time and haven't experienced any performance issues.

To enable logarithmic depth, create your renderer like this:

```js
const renderer = new THREE.WebGLRenderer({
 	logarithmicDepthBuffer: true,
	antialias: false // (Useless for render-to-texture pipelines)
});
```

**Comment by davidck** [comment]
Thank you so much for the in-depth help, it's really appreciated :)

Yeah, I'm **attempting** to render on a planetary scale, generating objects in based on camera position.   I didn't implement any advanced streaming techniques yet.   I'll definitely read more about the linear depth buffer as I learn / build my little experiment.

From a practical standpoint, the clipping off isn't a big issue at all as the sun will be grouped and positioned similarly to the star field (the player won't reach the sun / far away).  The project has a few fake / pseudo work arounds right now.

Here's another view with missing polygons:
<img width="1348" alt="screen shot 2019-03-07 at 12 08 24 pm" src="https://user-images.githubusercontent.com/135805/53974943-c4773500-40d1-11e9-8f14-3040910730a4.png">

I think it's really an issue with my setup, just need to figure out what.  There's no light source for the back of the ship when facing the god rays directly.  You can also see a far off planet (bottom of the screen) get partially cut off too.

**Comment by vanruesc** [comment]
Hm, have you tried enabling the logarithmic depth buffer? It does look like your near plane is cutting into your ship.

**Comment by davidck** [comment]
Yeah, setting it to use logarithmic depth buffer didn't help.
As said previously, everything works with just the rendering pass.

This is how it looks with just the rendering pass:

<img width="1362" alt="screen shot 2019-03-07 at 2 46 48 pm" src="https://user-images.githubusercontent.com/135805/53984755-f5fafb00-40e7-11e9-901f-d06e444e39f0.png">
<img width="1370" alt="screen shot 2019-03-07 at 2 46 41 pm" src="https://user-images.githubusercontent.com/135805/53984767-f98e8200-40e7-11e9-8665-e5d78157008d.png">
<img width="1354" alt="screen shot 2019-03-07 at 2 46 32 pm" src="https://user-images.githubusercontent.com/135805/53984770-fc897280-40e7-11e9-9924-4d3f95994b4b.png">

**Comment by davidck** [comment]
Not sure if this helps, but this is my render loop:

```
    this.sun.attachGodRay(this.cams[currentActiveCamera])
      .then((successMessage) => {
        if (!successMessage) return;
        console.log(successMessage);
      })
      .catch(err => console.log(err));

    // Would the LOD lines below affect the post processing?
    this.scene.updateMatrixWorld();
    this.scene.traverse((object) => {
      if (object instanceof THREE.LOD) {
        object.update(this.cams[currentActiveCamera].camera);
      }
    });

    this.cams[currentActiveCamera].camera.lookAt(this.ship.mesh.position);

    this.renderer.setSize(stageWidth, stageHeight);
    this.cams[currentActiveCamera].composer.render(delta);
```

**Comment by vanruesc** [comment]
Is there a reason why you're calling `Scene.updateMatrixWorld` manually? Did you also set `scene.matrixAutoUpdate` to `false`?

You should use `EffectComposer.setSize` instead of `WebGLRenderer.setSize`. (Calling both would be redundant.)

Still, I don't think that an image filter would cause these clipping artifacts. This library doesn't modify your cameras or scenes. The `GodRaysEffect` uses depth textures, but if those were failing, you'd simply see no light occlusion. A full code example that reproduces the issue would help a lot.

What are your system specs? Could be a hardware-related issue 🤔

**Comment by vanruesc** [comment]
Ping @davidck.

Currently, there is no clear indication of a bug in the `postprocessing` library. This issue will be closed in the next few days.

**Comment by davidck** [comment]
Ok, thanks for the help again @vanruesc 👍 
I'm still looking at it and will take more time, will close this one.

**Comment by vanruesc** [comment]
Alright, if you have any questions or find a potential bug just open a new issue!
