### ISSUE TITLE
Black screen with 6.0.1, 5.6.0 seems to work

### ISSUE THREAD

**Issue by nimloth05** [vanruesc/postprocessing#113]
I have the following feedle: https://jsfiddle.net/jbq91eah/ (the initial link to the lib is broken its an old example how to use `OutlinePass`, you have to replace it with a correct CDN link) 

If I set the release library to 6.0.1 (see CDN links at the bottom) I see a black screen. If I revert back to 5.6.0 everything seems to work. (I have the same problem with my project which pulls the NPM version of the library.)

5.6.0 https://cdn.jsdelivr.net/npm/postprocessing@5.6.0/build/postprocessing.umd.min.js
6.0.1https://cdn.jsdelivr.net/npm/postprocessing@6.0.1/build/postprocessing.umd.min.js

**Comment by vanruesc** [comment]
Hello,

the latest major version of `postprocessing` requires `three@0.102.x`. If you can't upgrade `three` in your environment, you'll need to use `postprocessing@5.6.0`.

**Comment by nimloth05** [comment]
Thanks for the info. After updating threejs, 6.0.1 is working fine. 

A note in the setup part of the readme or in the "troubleshoot black screens" would be nice (this problem cost me two hours )-: )

**Comment by vanruesc** [comment]
Thanks for the suggestion! I'll add a note to the wiki page.

The [release notes](https://github.com/vanruesc/postprocessing/releases) already contain hints about the required three.js version range. When you install `postprocessing` via NPM, you should also see a warning if no compatible version of `three` is installed.
