### ISSUE TITLE
OutlineEffect not work on my gltf model

### ISSUE THREAD

**Issue by jiangheng90** [vanruesc/postprocessing#117]
this is my init() function

    

      this.scene = new THREE.Scene()

      this.renderer = new THREE.WebGLRenderer({ antialias: true })
      this.renderer.setPixelRatio(window.devicePixelRatio)
      this.renderer.setSize(this.container.clientWidth, this.container.clientHeight)
      this.renderer.shadowMap.enabled = true
      this.container.appendChild(this.renderer.domElement)

      // PostProcess
      this.composer = new EffectComposer(this.renderer)

      this.renderPass = new RenderPass(this.scene, this.camera)

      this.outlineEffect = new OutlineEffect(this.scene, this.camera, {
        edgeStrength: 10,
        pulseSpeed: 0.0,
        visibleEdgeColor: 0xffffff,
        hiddenEdgeColor: 0x22090a,
        blur: false,
        xRay: true
      })

      const outlinePass = new EffectPass(this.camera, this.outlineEffect)
      this.renderPass.renderToScreen = true

      this.composer.addPass(outlinePass)
      this.composer.addPass(this.renderPass)

      let scene = this.scene
      let outlineEffect = this.outlineEffect
      // model
      let loader = new GLTFLoader()
      loader.load('http://localhost/Models/gltf/test.gltf', function (gltf) {
        gltf.scene.traverse(function (child) {
          if (child.isMesh) {
          }
        })
        gltf.scene.position.set(0, 20, 0)
        gltf.scene.rotation.set(-90 * Math.PI / 180, 0, 0)
        gltf.scene.scale.set(5, 5, 5)
        scene.add(gltf.scene)
        console.log(scene.children[3].children)
        //setup selection objects
        outlineEffect.setSelection(scene.children[3].children)
      })

I have set outlineEffect.setSelection while I load my Model

this is my function handle outlineEffect
`    addSelectedObject: function (object) {
      this.selectedObjects = []
      this.selectedObjects.push(object)
      this.outlineEffect.selectObject(object)
    }`

it appears nothing when i click in my scene, I'm not so sure where this issue comes from

here is my model on console
![Model](https://user-images.githubusercontent.com/1418843/55467419-d6e28100-5633-11e9-99b1-66a14fa8c2ba.PNG)

**Comment by jiangheng90** [comment]
![1](https://user-images.githubusercontent.com/1418843/55468856-ddbec300-5636-11e9-9d74-fa43d8edc730.PNG)
if I remove `this.composer.addPass(this.renderPass)` ,scene appears tobe like this

**Comment by vanruesc** [comment]
Hi,

try changing

```js
  this.renderPass.renderToScreen = true

  this.composer.addPass(outlinePass)
  this.composer.addPass(this.renderPass)
```

to

```js
  this.outlinePass.renderToScreen = true

  this.composer.addPass(this.renderPass)
  this.composer.addPass(outlinePass)
```

This allows the `RenderPass` to render the geometry to an internal frame buffer which can then be modified by the `EffectPass`.

**Comment by jiangheng90** [comment]
> 
      this.composer = new EffectComposer(this.renderer)
      this.renderPass = new RenderPass(this.scene, this.camera)

      this.outlineEffect = new OutlineEffect(
        this.scene,
        this.camera,
        {
          edgeStrength: 10,
          pulseSpeed: 0.0,
          visibleEdgeColor: 0xffffff,
          hiddenEdgeColor: 0x22090a,
          blur: false,
          xRay: true
        }
      )
      const outlinePass = new EffectPass(this.camera, this.outlineEffect)
      outlinePass.renderToScreen = true

      this.composer.addPass(this.renderPass)
      this.composer.addPass(outlinePass)
I have change my postprocessing part like u said 
emmmm....  seems it does not work 😥

**Comment by jiangheng90** [comment]
O I have found reason
frame have render twice in my update function
one in composer 
another one in `this.renderer.render(this.scene, this.camera)`
I think it my cover my composer frame😂
