### ISSUE TITLE
GodRay not using worldposition when updating

### ISSUE THREAD

**Issue by AlexAegis** [vanruesc/postprocessing#122]
Hi! Really cool library!

I noticed something when I started animating my "sun" to revolve around the center of the scene. 
The mesh moved but the effect stayed where it is. 

Turns out it's because of my "shortcut" of rotating the sun object. I have a THREE.Group at the center (0, 0, 0) and the sun is a children of that at (10, 0, 0). And I'm just rotating the parent group to move the sun. 

**But the god-ray effect always reads that (10, 0, 0) (The relative position) instead of the world position.**

Right now I solved this by switching my sun object to a pseudoSun (just another group), and copy the world-coordinates of that into my real sun's position when updating.

Is there a reason for the effect to use the position directly instead of WorldCoordinates?

**Comment by vanruesc** [comment]
Hi,

thanks for the issue report!

> Is there a reason for the effect to use the position directly instead of WorldCoordinates?

No, there is no reason. The `GodRaysEffect` was originally inspired by the god rays example from three.js which didn't account for this either. Until now there hasn't been a use case that reveiled this issue.

A fix is on the way.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.2.2`. Didn't test this thoroughly so let me know if you find a bug!

**Comment by AlexAegis** [comment]
Thanks! I just noticed that the package got updated. And, yes it works as it should. Thanks for the quick fix!
