### ISSUE TITLE
Having multiple outline effects, triggering one, triggers the other

### ISSUE THREAD

**Issue by AlexAegis** [vanruesc/postprocessing#125]
Hi! 

I have code snippets here but you can check my rendering pipeline [here](https://github.com/AlexAegis/loreplotter/blob/master/src/app/engine/engine.service.ts) everything is in this one file.

I have two Outline Effects with these test colors, and I have multiple objects of the same type to highlight.
```typescript
		this.hoverOutlineEffect = new OutlineEffect(this.stage, this.stage.camera, {
			blendFunction: BlendFunction.SCREEN,
			edgeStrength: 9,
			pulseSpeed: 0.0,
			visibleEdgeColor: 0x38ff70,
			hiddenEdgeColor: 0x30bf40,
			blur: 4,
			blurriness: 4,
			xRay: true
		});
		this.selectOutlineEffect = new OutlineEffect(this.stage, this.stage.camera, {
			blendFunction: BlendFunction.SCREEN,
			edgeStrength: 9,
			pulseSpeed: 0.0,
			visibleEdgeColor: 0xffff00,
			hiddenEdgeColor: 0x22090a,
			blur: false,
			xRay: true
		});
```

And my effectpass looks like this:
```typescript
		this.pass = new EffectPass(
			this.stage.camera,
			this.godRays,
			this.bloomEffect,
			this.hoverOutlineEffect,
			this.selectOutlineEffect,
			this.vignetteEffect
		);
		this.pass.renderToScreen = true;

		this.composer.addPass(this.renderPass);
		this.composer.addPass(this.pass);
```
And the render loop like this
```typescript
	private render() {
		requestAnimationFrame(() => this.render());
		TWEEN.update(Date.now());
		if (this.control) {
			this.control.update();
		}
		this.composer.render(this.clock.getDelta());
	}
```

I trigger the outlines with these (And respectively one for the other effect in a different place

```typescript
this.selectOutlineEffect.setSelection([item]),
this.selectOutlineEffect.deselectObject(item)
```

If I place console.logs before them i can see the I only trigger one, each time, and only once

This is how a 'selected' item looks like
(Here, I'm just selected the bottom sphere)
![image](https://user-images.githubusercontent.com/16900547/56855873-af8b8500-694f-11e9-89a3-7f7f4cc7c2bd.png)

And when I hover over another one, only that should light up

(Here, I'm hovering my mouse over the upper pink sphere)
![image](https://user-images.githubusercontent.com/16900547/56855880-c5994580-694f-11e9-8e43-a6c3e79dfa40.png)

Instead, both of them recieve the 'hover' effect.

Even if I take the 'Hover' effect out from the pass. (But leave the `this.hoverOutlineEffect.setSelection([item]),` in there) the other I left in still disappears.

(Here, I'm too hovering my mouse over the upper pink sphere)
![image](https://user-images.githubusercontent.com/16900547/56855937-8a4b4680-6950-11e9-834c-c0a97ecbd425.png)

**Comment by vanruesc** [comment]
Hi,

my guess is that the two `OutlinePass` instances are affecting each other because they use the same [selection render layer](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/OutlineEffect.js~OutlineEffect.html#instance-member-selectionLayer) for masking. Try the following:

```js
this.selectOutlineEffect.selectionLayer = 11;
```

If that doesn't help, I'll take a closer look.

**Comment by AlexAegis** [comment]
Yes, it did solve my problem, thank you! I didn't know about 'selection layers'.
