### ISSUE TITLE
runtime errors after npm update on Godrays effect / depthWrite

### ISSUE THREAD

**Issue by bendxr** [vanruesc/postprocessing#126]
Hi, 

With three 0.101.1 / postprocessing 5.6.0 : it was working fine.

After upgrade : 
three 0.103.0 or 0.104.0 / postprocessing 6.3.1 or 6.3.2 : 

I got the following runtime error in Chrome (Version 70.0.3538.67) : 

Uncaught TypeError: Cannot set property 'depthWrite' of undefined
    at new GodRaysEffect (postprocessing.esm.js:5088)
 [...]

and 2 others errors (but maybe they're consequences of the above one).

I noticed issue #123 seems to be slightly related to my problem but it indicates that bug has been solved...

Have you got any idea  ?

**Comment by vanruesc** [comment]
Hi bendxr,

the constructor signature of the `GodRaysEffect` has changed in [version 6.0.0](https://github.com/vanruesc/postprocessing/releases/tag/v6.0.0). Quoting from the changelog:

> - Changed signature to `constructor(camera, lightSource, options)`.
> - The type of the `lightSource` must now be `Mesh` or `Points` (was `Object3D`). The `depthWrite` property of its `material` will be set to `false` and the `transparent` flag will be set to `true`.

Major releases always introduce breaking changes. Just make sure to update your code when migrating to a new major version and you'll be fine 👌

**Comment by bendxr** [comment]
Ok, I'm sorry.
Effectively, updating my call to the constructor solved the issue.

Many thanks !

**Comment by vanruesc** [comment]
No problem. I'm glad I could help!
