### ISSUE TITLE
redundant three.js with A-FRAME

### ISSUE THREAD

**Issue by huhsame** [vanruesc/postprocessing#135]
Hello,
I have tried to use postprocessing with A-FRAME.

Since aframe has three, I installed postprocessing only.
Then, webpack printed error that is `Can't resolve 'three' in node_modules/postprocessing/build`.

after installing three as I am told,
my scene becomes weird. 
![image](https://user-images.githubusercontent.com/9151382/60645492-c4b2f180-9e73-11e9-9908-78592407e536.png)

here is the scene before installing three.
![image](https://user-images.githubusercontent.com/9151382/60645392-874e6400-9e73-11e9-81e5-0b0840e5b9e1.png)

How could I resolve it?

--

If I use CDN, it works without installing three.
![image](https://user-images.githubusercontent.com/9151382/60645983-2162dc00-9e75-11e9-9283-d4d2c0c4e3c9.png)

**Comment by huhsame** [comment]
I replaced `require('three') with `window.THREE` made by AFRAME in [this line](https://github.com/vanruesc/postprocessing/blob/3541bbe2124e1c0a4b72312f9b616e57b90febef/build/postprocessing.js#L7) for testing it.

The blurred scene still appears even with only one three of Aframe though.
Three.js doesn't matter.

**Comment by huhsame** [comment]
And I also have this code for antialiasing.

```

function load() {

    const assets = new Map();
    const loadingManager = new THREE.LoadingManager();

    return new Promise((resolve, reject) => {

        let image;

        loadingManager.onError = reject;
        loadingManager.onProgress = (item, loaded, total) => {

            if(loaded === total) {

                resolve(assets);

            }

        };

        // Load the SMAA images.
        image = new Image();
        image.addEventListener("load", function() {

            assets.set("smaa-search", this);
            loadingManager.itemEnd("smaa-search");

        });

        loadingManager.itemStart("smaa-search");
        image.src = PP.SMAAEffect.searchImageDataURL;

        image = new Image();
        image.addEventListener("load", function() {

            assets.set("smaa-area", this);
            loadingManager.itemEnd("smaa-area");

        });

        loadingManager.itemStart("smaa-area");
        image.src = PP.SMAAEffect.areaImageDataURL;

    });

}

// TODO create trigger after load the others
    load().then((assets) => {

        AFRAME.registerSystem("postprocessing", postprocessingSystem.setAssets(assets));

    }).catch(console.error);


```

**Comment by huhsame** [comment]
Hello, I completed the setting.
the reason is the order of code.

Sorry for this issue. 
I'm going to close it.

**Comment by arpu** [comment]
does this work in VR ?

**Comment by vanruesc** [comment]
> does this work in VR ?

Technically yes, but I don't have a VR headset and can't test `postprocessing` in an actual VR setting. So I can't guarantee that the effects will work as expected in all scenarios.

**Comment by dirkk0** [comment]
No, this doesn't work in VR, at least not on a Quest.

I've updated this example to 1.0.4 here:
https://gentle-glitter-close.glitch.me/
