### ISSUE TITLE
EffectComposer broken

### ISSUE THREAD

**Issue by rafalsk** [vanruesc/postprocessing#144]
EffectComposer seems to be broken with current THREE.js builds.
I tried to retireve latest one from THREE.js examples repo with no luck; the one included in POSTPROCESSING lib. also seems incompatible.
Gives:

"Uncaught TypeError: renderer.getDrawingBufferSize is not a function
    at new THREE.EffectComposer (EffectComposer.js:30)"

**Comment by vanruesc** [comment]
Hi,

that's weird 🤔 The [getDrawingbufferSize](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L405) still exists in `r109dev` and the three.js folks always deprecate public methods before removing them. Are you sure, you're passing a `WebGLRenderer` instance to the `EffectComposer` constructor?

I haven't gotten around to updating `postprocessing` for `three@0.108.0` yet. Judging by the [release notes](https://github.com/mrdoob/three.js/releases/tag/r108), there shouldn't be any issues, but using the latest release isn't guaranteed to work yet.

**Comment by rafalsk** [comment]
vanruesc; please close the ticket; or I shall update the information; I was using CanvasRenderer instead of WEBGLRenderer and the former lacks the getDrawingBufferSize() function; we could try to find a way to support the former; maybe I could find some time; as for now - sorry for not providing complete and accurate information and thank you for the library.

**Comment by vanruesc** [comment]
Ok, no problem!

> we could try to find a way to support the former

The `CanvasRenderer` was moved from core to the three.js examples in r69 back in 2014 and then later removed from the examples in r98 (2018). There is no point in supporting it since it's dead 😇
