### ISSUE TITLE
Feedback Filter

### ISSUE THREAD

**Issue by torinmb** [vanruesc/postprocessing#145]
I'm looking to implement a feedback filter and I'm wondering if you could point me in the right direction.

I was initially working off [this example](https://discourse.threejs.org/t/basic-feedback-and-buffer-implementation-with-glsl-shaders/409). The idea is to be able to create a trail effect for either your scene or a video texture. 

My initial attempt was to extend and Effect, but I'm assuming I'll actually need to set this up as its own render pass. From my understanding, the idea is to have a SavePass save the scene to a render target and pass the texture of the render target into the Feedback filter's shader, along with a texture of the current scene. Then Mix between the two textures for the final color.
Then in the render loop switch the values of the two textures to ping-pong between them.

Here was my initial setup:
``` javascript
import * as THREE from 'three';
import { BlendFunction, Effect} from "postprocessing";

let fragmentShader = `
uniform sampler2D bufferTexture;//Our input texture
uniform sampler2D sceneTexture;
uniform float mixAmount;

void mainImage(const in vec4 inputColor,const in vec2 uv,out vec4 outputColor){
    vec2 uv2 = inputColor.xy;
    uv2 = mix(vec2(0.5), uv2, .9); // this could be passed in as a uniform for more control
    vec4 sum = texture2D(bufferTexture, uv2);
    vec4 src = texture2D(sceneTexture, uv2);
    sum.rgb = mix(sum.rbg, src.rgb, mixAmount);
    outputColor = sum;
}
`;

export class FeedbackEffect extends Effect {
    constructor({ blendFunction = BlendFunction.NORMAL, bufferTexture, sceneTexture, mixAmount = 0.01} = {}) {
        super("FeedbackEffect", fragmentShader, {
			blendFunction,
			uniforms: new Map([
                ["mixAmount", new THREE.Uniform(mixAmount)],
                ["bufferTexture", new THREE.Uniform(bufferTexture.texture)],
                ["sceneTexture", new THREE.Uniform(sceneTexture.texture)]
			])
		});
	}
}
```
Then in the render loop switch the value of the bufferTexture and sceneTexture. Ideally this would be done within the class if the Effect exposes a render function.

Any help would be greatly appreciated! Thanks!

**Comment by vanruesc** [comment]
Hi,

It should be possible to implement this kind of effect by extending `Effect`. Effects have an [update](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/Effect.js~Effect.html#instance-method-update) method that can be overridden to render things before the effect's main shader gets executed. The `inputBuffer` parameter contains the current scene colors.

I might be able to provide more tips tomorrow, if I find the time. Need to catch some sleep first 😄

**Comment by vanruesc** [comment]
I managed to look at this today and it turns out that this effect is a little bit more difficult to implement than I thought.

The `FeedbackEffect` itself is actually a more complex `TextureEffect`. The main shader simply draws the generated feedback result. The shader that calculates the feedback colors has to be implemented as a custom shader material which is used in an internal `ShaderPass` that updates the feedback texture.

Here's an example implementation: https://jsfiddle.net/315af0gu/

If you have any questions, feel free to ask.

**Comment by jpweeks** [comment]
This is the type of effect I was describing in this issue: https://github.com/vanruesc/postprocessing/issues/131. In my case, I usually want to apply other effects (blur, transform / scale) to the feedback buffer before compositing and feeding back to the effect chain input.

**Comment by vanruesc** [comment]
> This is the type of effect I was describing in this issue: #131.

Does that mean the given example solves your issue as well? :o

Actually, I'd rather call this effect `AfterimageEffect` instead of `FeedbackEffect` since it's just accumulating decaying frames in a linear fashion.

If you're concerned about performance, this example is optimal as far as I can tell. The resources are also minimal considering that reading from a render target and writing to it at the same time must be avoided.

**Comment by jpweeks** [comment]
> Does that mean the given example solves your issue as well? :o

Not completely, as it's still a linear effect chain, and it doesn't feed back to the beginning of the chain (before the render pass). I think some API for non-linear (branching) inputs/outputs is what is needed to do feedback.

**Comment by vanruesc** [comment]
> it doesn't feed back to the beginning of the chain (before the render pass)

Wouldn't that be easy to do, though? You could grab `renderTarget0.texture` and feed that into any renderable object that can use it (say, as a `map`) or into any other custom effect or pass.

> it's still a linear effect chain

Even if _something_ feeds back into the first `RenderPass`, the whole process is still linear. Even if there's branching, it's still linear. I don't understand what you mean by "non-linear" 😵

**Comment by jpweeks** [comment]
Yeah, you can reach into an effect and grab render target textures, which is what I currently do, but this feels a bit hacky, and can break if the effect or composer swaps a render target. 

> Even if there's branching, it's still linear

Is there an API for branching? The only way I could find to do it with the current API is to have multiple composers. Maybe it's too complicated, but it'd be nice to be able to write an effect graph similar to how Blender's material editor works; that's essentially what I mean by non-linear: a node graph (Blender Material Nodes) vs effect stack (Photoshop Layers).

**Comment by vanruesc** [comment]
Let's continue this discussion in #131.

**Comment by vanruesc** [comment]
Closing this now since it seems to be resolved.

@torinmb If the provided example doesn't fully solve your issue, feel free to re-open!
