### ISSUE TITLE
Please help a noob adding SMAA effect pass!

### ISSUE THREAD

**Issue by kevinshane** [vanruesc/postprocessing#147]
Hi gurus, I am try to use SMAA for a test gltf scene but I don't know how it works. I also try to look through demo source file but it seems too complicated for me.
I have created a jsfiddle playing around other effects and it works fine, except the smaa pass of cause
https://jsfiddle.net/kevinshane/s0jy14g7/61/
would you please guide me through this? Thank you so much

**Comment by vanruesc** [comment]
Hi,

I recommend loading all assets first. Afterwards, set up the scene and start rendering:
https://jsfiddle.net/n6uq0yto/

In this example I use the [LoadingManager](https://threejs.org/docs/#api/en/loaders/managers/LoadingManager) from `three` to track loaded and pending files.

I think it all becomes much clearer by doing it this way. The code should be self-explanatory, but if you have any questions feel free to ask.

**Comment by vanruesc** [comment]
Closing as it seems to be resolved.
