### ISSUE TITLE
EffectComposer.setSize needs updateStyle parameter

### ISSUE THREAD

**Issue by speigg** [vanruesc/postprocessing#150]
`EffectComposer.setSize` doesn't allow `Renderer.setSize` to be called with the `updateStyle` parameter set to `false`. Please add a third parameter to `EffectComposer.setSize` which is forwarded to `Renderer.setSize`. Thanks!

**Comment by vanruesc** [comment]
Thanks for pointing that out! I'll look at this in a bit.

**Comment by speigg** [comment]
Thanks for the quick fix!
