### ISSUE TITLE
Outline doesn't disappear on deselect...

### ISSUE THREAD

**Issue by quacrobat** [vanruesc/postprocessing#159]
Hi, thanks for a great library!
I migrated from an earlier version of Three.js (90 to 110) and the latest postprocessing and now a weird bug has appeared: 

- I have a mesh in the scene, when I select it, it gets correctly outlined. 
- If I select another mesh it correctly removes the outline from the first and puts it on the second mesh.
- But if I deselect everything by clicking outside the mesh, the outline doesn't disappear, and actually remains as a ghost outline even if I move the camera therefore causing the frame to render.
I am calling `_scope.outlineEffect.selection.set(objects);` from an onclick event listener where `objects`  is an array of the selected meshes, and this had been working perfectly before.

There are no errors in the console, and I tried everything to no avail. What am I doing wrong here?

![outline bug](https://user-images.githubusercontent.com/4062597/68520544-34f9d580-02a1-11ea-8d25-c9f2b6525815.gif)

```js
function start(assets) {

	// Effects    
	_scope.outlineEffect = new POSTPROCESSING.OutlineEffect(_scope.main, _scope.camera, {
		blendFunction: POSTPROCESSING.BlendFunction.ALPHA,
		edgeStrength: 10,
		visibleEdgeColor: 'yellow',
		hiddenEdgeColor: 'yellow',
		height: 960,
		blur: false
	});

	// Passes
	const renderPass = new POSTPROCESSING.RenderPass(_scope.main, _scope.camera);
	_scope._composer.addPass(renderPass);
          
	const outlinePass = new POSTPROCESSING.EffectPass(_scope.camera, _scope.outlineEffect);
	outlinePass.renderToScreen = true;
	_scope._composer.addPass(outlinePass);        

}
```

Thanks for any ideas!

**Comment by vanruesc** [comment]
Hi,

There seems to be a problem with how you select and deselect objects. Please provide all code that interacts with `_scope.outlineEffect.selection`.

> I migrated from an earlier version of Three.js (90 to 110) and the latest postprocessing

Are you sure that you're using `postprocessing@6.8.8`? Using a CDN with versions such as `@latest` might still give you an outdated version in some cache-related situations.

**Comment by vanruesc** [comment]
Oh, also make sure you're providing the frame delta time to `EffectComposer.render`:

```js
_scope._composer.render(_scope.clock.getDelta());
```

**Comment by quacrobat** [comment]
> ```js
> ```js
> _scope._composer.render(_scope.clock.getDelta());
> ```
Thank you! that did the trick, I was missing the clock.
added `_scope.clock =new THREE.Clock();` before.
