### ISSUE TITLE
TextureEffect example code

### ISSUE THREAD

**Issue by GoogolHz** [vanruesc/postprocessing#162]
I've been trying to get TextureEffect working, and I can't figure out what I'm doing wrong. I've tried looking under the hood of your example at: https://vanruesc.github.io/postprocessing/public/demo/#texture
...but the code is minified, and I can't sort it out.
If there is a way for me to look at sample code for this effect, I would be most grateful. 
Thanks for this terrific and most useful post processing library!

**Comment by vanruesc** [comment]
Hi,

the source code of the demo can be found here: https://github.com/vanruesc/postprocessing/blob/master/demo/src/demos/TextureDemo.js#L142

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
