### ISSUE TITLE
Typescript implementation

### ISSUE THREAD

**Issue by nagman** [vanruesc/postprocessing#166]
Hi,
Will this package be implemented with types?
Thanks

**Comment by vanruesc** [comment]
Hello,

sorry, but there are no plans to introduce TypeScript or PureScript in this project. I much prefer standard JS for various reasons and believe that TypeScript will become obsolete as soon as more type-related features arrive in standard JS.

**Comment by gigablox** [comment]
You speak the language of my people. @vanruesc

**Comment by bastienrobert** [comment]
But for any people who wants to use typescript on their projects without setting `// @ts-ignore` comment before each import of postprocessing, you can still use [dts-gen](https://github.com/Microsoft/dts-gen) to create definitions 🙂
