### ISSUE TITLE
is postprocessings ssao the same as three's own?

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#169]
i am trying to make sense of the effect, but i don't get near to the ssao effect in three/examples. this is how it looks in the original: https://codesandbox.io/s/react-three-fiber-react-spring-8fo01 (Effects.js)

<img width="338" alt="Screenshot 2020-01-24 at 14 30 52" src="https://user-images.githubusercontent.com/2223602/73072773-27261a80-3eb6-11ea-9ce4-73c088151f92.png">

and here's my attempted port: https://codesandbox.io/s/react-three-fiber-react-spring-z7tt5 (Effects.js)

<img width="395" alt="Screenshot 2020-01-24 at 14 31 50" src="https://user-images.githubusercontent.com/2223602/73072834-4755d980-3eb6-11ea-8f5c-6b101da8e139.png">

in the original ssao these boxes look like they throw shadows, postprocessings ssao seems to be more concerned with making individual object faces pop out.

i've tried shifting the config back and forth, but haven't gotten relatable results so far. both sandboxes have the same near/far plane settings. is there anything i could improve?

**Comment by vanruesc** [comment]
Hi,

you forgot to add the `normalPass` to the composer 💥 

I've also adjusted the SSAO settings to account for your camera settings: 
https://codesandbox.io/s/react-three-fiber-react-spring-kml6w

Note that the distance thresholds and falloffs depend on your camera near and far plane settings.

Btw: I noticed the SMAA loader fix; I'll add a fix for that when I get a chance.

**Comment by vanruesc** [comment]
Oh, and to answer your question: no, the SSAO implementation in this library is not the same as the one found in the three.js examples. It uses a spiral sampling pattern and doesn't blur the shadows, which gives it a grainier look. The advantage is that it's more accurate and exhibits less haloing.

The current SSAO implementation in three uses a randomized sampling pattern and blurs the result.

**Comment by drcmda** [comment]
wow, that's awesome! thanks for the help! i think it looks great now.

> Btw: I noticed the SMAA loader fix; I'll add a fix for that when I get a chance.

Is there a fix for this? THREE.Loader.load goes (url, onLoad, onError), that's what i've modelled useLoader after. but smaaloader doesn't seem to need the url arg.

**Comment by vanruesc** [comment]
> Is there a fix for this?

It should be possible to emulate method overloading by checking whether the first parameter is a function or not. The number of arguments also plays a role, I think.

**Comment by vanruesc** [comment]
@drcmda `SMAAImageLoader` now properly extends `three~Loader` in `postprocessing@6.11.0`.

**Comment by drcmda** [comment]
thanks so much!
