### ISSUE TITLE
GammaCorrectionShader, linear -> srgb

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#170]
Is there something like threejs new [GammaCorrectionShader](https://github.com/WestLangley/three.js/blob/a72e0ba0ef22aa3570dc63b85e45153f33c6fc1b/examples/js/shaders/GammaCorrectionShader.js) in postprocessing?

In threes effects add-on we have to use GCS as a pass now in order to covert linear colorspace to sRGB: https://codesandbox.io/s/r3f-lod-50y03

I'm trying to get a similar result in postprocessing: https://codesandbox.io/s/r3f-ibl-envmap-normalmap-be9v8

**Comment by drcmda** [comment]
Saw GammaCorrectionEffect, i guess it's the same ... (?)

**Comment by vanruesc** [comment]
@drcmda The `GammaCorrectionEffect` can be used but there a few things to note:
1. The `GammaCorrectionShader` from `three` now uses `LinearTosRGB` while the `GammaCorrectionEffect` still uses `LinearToGamma`.
2. The internal frame buffers of the `EffectComposer` currently use `UnsignedByteType`. The conversion from linear color space to Gamma or sRGB with only 8 bits per channel will degrade image quality.

Proper color space encoding is already implemented on the dev branch and will be included in the next release. The new API will allow you to simply specify `WebGLRenderer.outputEncoding` as usual and `postprocessing` will follow suit (internal render operations will still be performed in linear color space).

Additionally, you'll be able to enable high precision frame buffers across passes and effects via a new parameter:

```js
const composer = new EffectComposer(renderer, {
	frameBufferType: HalfFloatType
});
```

**Comment by drcmda** [comment]
@vanruesc that's fantastic! i wondered why this has to be so complicated in threes composer, pp reading out outputEncoding seems like a nicer approach. thank you so much, can't wait to try it!

**Comment by vanruesc** [comment]
@drcmda `postprocessing@6.11.0` now supports color space encoding as described above.

**Comment by drcmda** [comment]
@vanruesc i updated my example: https://codesandbox.io/s/r3f-ibl-envmap-normalmap-yjevf but it brightens everything up. is there a step that i forgot to take?

**Comment by drcmda** [comment]
edit: just me being silly, bloom was set to 0, affecting everything. the new update works great! 👍

**Comment by drcmda** [comment]
edit: it works when encoding is set to the default value (linear), but sRGB seems to set it off

**Comment by vanruesc** [comment]
Converting linear colors to sRGB is a different workflow which requires changes to the scene lighting and diffuse colors. Going from linear to sRGB or Gamma makes everything brighter.

Textures that are already in sRGB color space need to be declared as such:

``` js
texture.encoding = sRGBEncoding;
```

The `GLTFLoader` automatically sets the encoding of diffuse maps to `sRGBEncoding`. Other textures that contain data, such as normal maps, need to use `LinearEncoding` which is the default setting.

**Comment by vanruesc** [comment]
I looked at the example but couldn't figure out what the `setActive` function does. Are you sure that the system uses the same `WebGLRenderer` instance that has `encoding` still set to `sRGBEncoding` after disabling the effects?

After clicking on the button "switch effects off" I would expect to see the same bright image without the bloom effect.

If you disable the effects right from the beginning and comment out the line where you set the encoding to `sRGBEncoding`, the result still remains dark which means that the encoding setting doesn't seem to do anything for the normal render mode.
