### ISSUE TITLE
SSAOPass: Improve depth precision with WebGL 2.

### ISSUE THREAD

**Issue by arpu** [vanruesc/postprocessing#174]
should this be done here https://github.com/vanruesc/postprocessing/blob/d4576c14fa36e857ffc5f1bab2f1c28a1e79492e/src/core/EffectComposer.js#L193 ? 

https://github.com/mrdoob/three.js/pull/18672

**Comment by vanruesc** [comment]
Thanks for letting me know! I'm looking into it.

**Comment by vanruesc** [comment]
The type of the depth texture has been changed to `UnsignedIntType` in `postprocessing@6.12.1`.
