### ISSUE TITLE
Trouble managing selective bloom and outline independently

### ISSUE THREAD

**Issue by leefsmp** [vanruesc/postprocessing#191]
I would like to use outline upon mouse hovering a mesh and selective bloom when mesh gets actually selected.

In the following sample I am unable to do so, it seems than bloom is always coming up even if the mesh has not been added to `bloomEffect.selection.add(selectedObject)`. Is this a bug in the library or I am doing something stupid? 

[demo](https://codesandbox.io/s/selective-bloom-outline-kfcwf?file=/src/App.js:4531-4572)

Second connected question, I would like to use bloom effects of different intensity, for example the selected mesh is intensity 0.5 and some other elements in my scene would have a higher intensity so they are emphasised.  Is it doable? I was trying to create 2 SelectiveBloom with different intensity but the stronger seems to be applied.

Thanks

**Comment by vanruesc** [comment]
If you'd like to use multiple selective effects together with each of them using a separate selection set, you need to adjust the dedicated selection layer for each effect:

```js
outlineEffect.selection.layer = 10; // Default layer for a new selection sets.
bloomEffect1.selection.layer = 11;
bloomEffect2.selection.layer = 12;
``` 

This should also fix your issue with multiple bloom effects. Keep in mind that selective bloom is already quite heavy as it needs to render your scene a second time for proper occlusion. The more objects you have in your scene, the worse it gets. The same goes for the outline effect.

**Comment by vanruesc** [comment]
> [...] for example the selected mesh is intensity 0.5 and some other elements in my scene would have a higher intensity so they are emphasised. Is it doable? I was trying to create 2 SelectiveBloom with different intensity

That's a valid approach. Alternatively, you could try to adjust the [emissive](https://threejs.org/docs/#api/en/materials/MeshStandardMaterial.emissive) color of selected objects.

**Comment by leefsmp** [comment]
Awesome, thank you!

**Comment by leefsmp** [comment]
A side question on that, does it makes a difference in terms of performance whether I have two `EffectPass` (so I can disable them independently) or a single one that combines bloom and outline effects?

**Comment by vanruesc** [comment]
It does make a difference. If you combine bloom and outline in one pass, both effects will be rendered using one fullscreen render operation.

In this case, I recommend creating three `EffectPass` instances: one that only contains the outline effect, one that only contains the bloom effect and one that contains both effect instances. Effects can be reused by multiple different effect passes which can then be enabled/disabled as needed.

**Comment by leefsmp** [comment]
ok, so it means if I want both bloom and outline at the same time, I will disable the first 2 independent passes and enable the combined one?

**Comment by vanruesc** [comment]
Exactly.

**Comment by leefsmp** [comment]
Thanks!
