### ISSUE TITLE
DepthOfField issue

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#223]
sandbox: https://codesandbox.io/s/5zt8n?file=/src/App.js (it prints out the real dofProps in the console)

i can't seem to figure out how this effect is working, all i want is the bear to be in focus while the foreground blurs out. i have distributed the planes along the z axis, the bear is at 0/0/0 and the palm leaves on 0/0/10 and 0/0/20. the background is minus that. but whatever values i try, it seems everything goes blurry at the same time. 

is there anything else i need to do? i've tried to emulate the dof example as best as i could.

the abstracted code that's managed by rpp is:

```jsx
const composer = new EffectComposerImpl(gl, { multisampling, frameBufferType: HalfFloatType, ...props })
composer.addPass(new RenderPass(scene, camera))
const pass = new NormalPass(scene, camera)
composer.addPass(pass)
const dof = new DepthOfFieldEffect(camera, dofProps)
const effectPass = new EffectPass(camera, dof)
composer.addPass(effectPass)
effectPass.renderToScreen = true
```

**Comment by gsimone** [comment]
My hypothesis here is that the depthBuffer is a single value, because one of the planes is on front of the camera, occluding everything else - thus having only one level of depth.

Is there a way to manually set the depthBuffer for depthOfField? 
That way wecould manually compose the layers ( using only the alpha channel of the images ) and let the dof do its thing

**Comment by vanruesc** [comment]
I think @gsimone is right, but the planes in this scene are actually transparent which means that none of them write depth. You can use `<Depth/>` to visualize the depth that the `EffectPass` is working with.

> Is there a way to manually set the depthBuffer for depthOfField?

Yes, it's possible to use a custom depth texture:

```js
import { RGBADepthPacking } from "three";
import { DepthPass, EffectPass } from "three";

const depthPass = new DepthPass(scene, camera);
const effectPass = EffectPass(camera, ...effectsThatUseDepth);

// Doing this will disable the automatic creation of a depth texture.
effectPass.setDepthTexture(depthPass.texture, RGBADepthPacking);

composer.addPass(depthPass);
composer.addPass(effectPass);
```

Also not that `focusDistance` and `focalLength` should be in the range `[0, 1]`. The bokeh scale is a simple scale `[0, Infinity]`:

```js
const focusDistance = useControl("focus distance", { type: "number", value: 0, min: 0, max: 1 })
const focalLength = useControl("focal length", { type: "number", value: 0.048, min: 0, max: 1 })
const bokehScale = useControl("bokeh scale", { type: "number", value: 2, min: 0, max: 5 })
```

**Comment by drcmda** [comment]
@vanruesc @gsimone solved it with a custom material discarding pixels where alpha < 0.1, quick and easy :-) http://frail-change.surge.sh
