### ISSUE TITLE
How handle pixelRatio?

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#232]
For reference: https://github.com/pmndrs/react-postprocessing/pull/29

We noticed that output is blurry even if the webglrenderer is on a higher pixelratio. And this was supposed to fix it:

```diff
-    useEffect(() => void composer.setSize(size.width, size.height), [composer, size])
+    useEffect(() => void composer.setSize(
+      size.width * window.devicePixelRatio,
+      size.height * window.devicePixelRatio
+    ), [composer, size, window.devicePixelRatio])
```

But it seems that it just scales the output.

We then tried: https://github.com/pmndrs/react-postprocessing/pull/30

```diff
+    const pixelRatio = gl.getPixelRatio()
-    useEffect(() => void composer.setSize(
-      size.width * window.devicePixelRatio,
-      size.height * window.devicePixelRatio
-    ), [composer, size, window.devicePixelRatio])
+    useEffect(() => {
+      composer.setSize(size.width * pixelRatio, size.height * pixelRatio)
+    }, [composer, size, pixelRatio])
```

Same issue it seems.

Is there a definitive way to adjust the ratio, and can it be altered once the effectcomposer has been created?

**Comment by drcmda** [comment]
never mind, browsing pp source it seems straight forward

```jsx
// Update the logical render size.
renderer.setSize(width, height, updateStyle);

// The drawing buffer size takes the device pixel ratio into account.
const drawingBufferSize = renderer.getDrawingBufferSize(new Vector2());
```

it sets the size, fetches drawing buffer size. it should be automatic ... and in case PR is changed, calling composer.setSize() should be enough to adapt.

**Comment by vanruesc** [comment]
Right, setting the ratio via [renderer.setPixelRatio(ratio)](https://github.com/vanruesc/postprocessing/blob/4fbd2bdb4179cbf142154af16d28e6c76cd8da7b/demo/src/index.js#L89) is the recommended way to do this and calling `composer.setSize()` without arguments will update the buffer size.

My phone has a pixel ratio of `3.0` and renders the postprocessing demos correctly.

**Comment by drcmda** [comment]
i am working on adaptive performance where standstill is highest, and when things move it can dial down some settings with a small lerp so it doesn't look as harsh. i was wondering why it never got to 60fps with effects, but now it's clear. calling setSize really did the trick! thanks! :-)
