### ISSUE TITLE
Attempt to use multiple EffectComposers to enhance rendering performance

### ISSUE THREAD

**Issue by leefsmp** [vanruesc/postprocessing#233]
Greetings! It isn't a bug report strictly speaking but rather a question wondering if I'm using the lib properly.

Here is the scenario: I render a large factory populated with multiple assets, could also be a building filled up with furnitures. The scene can get pretty heavy to render due to number of different meshes and we want to make interaction with the model as smooth as possible for the user, so we came up with the idea of rendering only the building during orbit and other interactions, then render all the assets if no interaction, that way it could be smoothly navigated. 

I initially tried Three.js layers, placing all assets on a different layer and disabling it while navigating, which worked to some extent but the initial toggle of the assets layer was slow. So I then tried to managed two scenes, one for the model itself, the other containing all those assets. I added two consecutive `RenderPass` to my `EffectComposer`, then at the beginning  of a user interaction I disable the asset RenderPass to just keep the model RenderPass. This works but it seems to have no performance benefit, as if the assets were still visible when rendering the scene.

I now switched to having two almost identical `EffectComposer` one with the 2 render passes, another with just the model pass and I switch which composer is being rendered based on if there is user interaction or not. Unfortunately it's still behaves poorly. Here is the code of my Composer, the second one is similar except it has less effects and no assetPass:

```js
async createComposer () {

  const composer = new EffectComposer(this.renderer, {
    frameBufferType: THREE.HalfFloatType
  })

  // ---------- BACKGROUND PASS ----------

  this.backgroundPass = new RenderPass(
    this.background.scene, 
    this.background.camera)

  composer.addPass(this.backgroundPass)

  // ---------- SCENE PASS ----------

  this.renderPass = new RenderPass(
    this.scene, this.camera)

  this.renderPass.clear = false

  composer.addPass(this.renderPass)

  // ---------- ASSET PASS ----------

  this.assetPass = new RenderPass(
    this.assetScene, this.camera)

  this.assetPass.clear = false

  composer.addPass(this.assetPass)

  // ---------- BLOOM PASS ----------

  this.bloom = new SelectiveBloomEffect(
    this.assetScene, this.camera, {
      luminanceThreshold: 0.1,
      luminanceSmoothing: 0.5,
      intensity: 1.0
    })

  this.bloom.ignoreBackground = true
  this.bloom.selection.layer = 11

  this.bloomPass = new EffectPass(
    this.camera, this.bloom)   

  composer.addPass(this.bloomPass)

  // ---------- OUTLINE PASS ----------

  this.outline = new OutlineEffect(
    this.assetScene, this.camera, {
      visibleEdgeColor: '#87CEFA',
      hiddenEdgeColor: '#87CEFA',
      edgeStrength: 15.0,
      blur: false
    })
  
  this.outline.selection.layer = 10

  const [search, area] = await loadSMAA()

  const smaa = new SMAAEffect(
    search, area)

  smaa.edgeDetectionMaterial.
    setEdgeDetectionThreshold(0.05)

  this.outlinePass = new EffectPass(
    this.camera, smaa, this.outline)   

  composer.addPass(this.outlinePass)

  // ---------- SSAO PASS ----------

  const normalPass = new NormalPass(
    this.assetScene, this.camera)

  this.ssao = new SSAOEffect(this.camera, 
    normalPass.renderTarget.texture, {
    blendFunction: BlendFunction.MULTIPLY,
    distanceThreshold: 0.02,	// Render up to a distance of ~20 world units
    distanceFalloff: 0.0025,	// with an additional ~2.5 units of falloff.
    rangeThreshold: 0.0003,		// Occlusion proximity of ~0.3 world units
    rangeFalloff: 0.0001,			// with ~0.1 units of falloff.
    luminanceInfluence: 0.7,
    samples: 11,
    radius: 30,
    scale: 1.0,
    bias: 0.05,
    rings: 4
  })
  
  this.ssaoPass = new EffectPass(
    this.camera, this.ssao)

  this.ssaoPass.enabled = false

  composer.addPass(this.ssaoPass)

  // ---------- GAMMA PASS ----------

  this.gamma = new GammaCorrectionEffect({ 
    gamma: 2.2 
  })

  const gammaPass = new EffectPass(
    this.camera, this.gamma)

  gammaPass.encodeOutput = false

  composer.addPass(gammaPass)

  return composer
}

render = (optimize) => {
  if (this.optimizeRendering && optimize) {
    clearTimeout(this.optimizedTimeout)
    this.optimizedTimeout = setTimeout(() => {
      this.optimizedTimeout = 0
      this.optimized = false
      this.render()
    }, 250)
    if (!this.optimized) {
      this.optimized = true
      return this.render()
    }
  }

  this.optimized
    ? this.optimizedComposer.render()
    : this.composer.render()
}
```  

Am I doing something stupid or is there some kind of limitation that prevents from running smoothly when switch the composers in render method?

Appreciate any insights on the topic. Thanks in advance.

**Comment by vanruesc** [comment]
The problem with this setup is that `RenderPass`, `SelectiveBloomEffect`, `OutlineEffect` and `NormalPass` all render `assetScene` so you're always rendering the asset objects 4 times per frame. This will result in lots of draw calls which is obviously very bad for performance. I'd suggest adding all you asset items to a `Group` that lives in your main scene. You can then use a `LambdaPass` (added in `postprocessing@6.18.0`) to hide this group during camera movement:

```js
const scene = new Scene();
const camera = new PerspectiveCamera(...);
const assetObjects = new Group();

const composer = new EffectComposer(...);

const renderPass = new RenderPass(scene, camera);
const effectPass = new EffectPass(camera, ...effects);
const lambdaPass = new LambdaPass(() => {

	// cameraIsMoving would be changed based on user input.
	assetObjects.visible = !cameraIsMoving;

});

composer.addPass(lambdaPass);
composer.addPass(renderPass);
composer.addPass(effectPass);
```

I haven't had time to actually test this, but that's the general idea. 

Another thing I noticed is that you use strings like `'#87CEFA'` for the edge colors. This will probably not work because the parameter expects a hexadecimal number in the form `0x87CEFA`. Lastly, I don't recommend using multiple `EffectComposer` instances.

**Comment by vanruesc** [comment]
Actually the `LambdaPass` isn't even necessary: you could just set `assetObjects.visible` in your input handler.

**Comment by leefsmp** [comment]
Thanks for the feedback, we have settings to toggle the various rendering effects so we can switch those off as needed, but assets need to be selectable and selection is done with bloom and outline to avoid changing the material to another colour for example, as most assets are textured compound objects so colouring them is not a very good option.

I found out that removing the group from the scene and adding it back provides better results while interacting with the model, however the initial switch between non-optimized > optimized modes still provokes a lag in the interaction so I think I would need to investigate deeper into implementing a customized renderer.
