### ISSUE TITLE
Set edge thickness of outline effect

### ISSUE THREAD

**Issue by CharlieHess** [vanruesc/postprocessing#235]
### Is your feature request related to a problem?
I'm trying to set the thickness of outlines and can't find a related property. Is there a way to set the thickness?

### Describe the solution you'd like
The `OutlinePass` from three.js, for example, has an `edgeThickness` property.

### Describe alternatives you've considered
I could go back to using the `threejs/examples` effect, but I'm trying to convert my effects over to this.

**Comment by vanruesc** [comment]
Edge thickness is just an alias for the [blur kernel radius](https://github.com/mrdoob/three.js/blob/8e3b6b83a690119a0488b439b7e02275dc434698/examples/jsm/postprocessing/OutlinePass.js#L375) in three's implementation. You can control the outline edge thickness in `postprocessing` via the  [OutlineEffect constructor parameters](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/OutlineEffect.js~OutlineEffect.html#instance-constructor-constructor) `kernelSize` and `edgeStrength`, for example:

```js
const effect  = new OutlineEffect(scene, camera, {
	blendFunction: BlendFunction.SCREEN,
	kernelSize: KernelSize.SMALL, // Edge thickness
	edgeStrength: 10.0,
	pulseSpeed: 0.0,
	visibleEdgeColor: 0xffffff,
	hiddenEdgeColor: 0x22090a,
	height: 480,	// Also influences edge thickness
	blur: true,	// Enable blurring
	xRay: true
});
```

It's also possible to change the kernel size and edge strength later:

``` js
effect.blur = true;
effect.blurPass.kernelSize = KernelSize.LARGE
effect.uniforms.get("edgeStrength").value = 123.4;
```

**Comment by CharlieHess** [comment]
Aha, the piece I was missing was that `blur` must be set to true. If it's set to `false` the strength and kernel size have no effect: it remains a tiny thin line.
