### ISSUE TITLE
White screen when adding new EffectPass

### ISSUE THREAD

**Issue by BaptisteAugment** [vanruesc/postprocessing#236]
Hi, 

I'm using ThreeJs to render a GLTF. I want to use postprocessing for creating an Outline effect and others, but it's not working. I try with almost all effects. When i doing this, all is working : 
```js
this.configuration.compose = new EffectComposer(this.three.renderer);
var camera = this.sendCam();
var renderPass = new RenderPass(this.three.scene, camera);
this.configuration.compose.addPass(renderPass);
```

But, when i add an EffectPass, i got an white screen, like this : 
```js
this.configuration.compose = new EffectComposer(this.three.renderer);
var camera = this.sendCam();
var renderPass = new RenderPass(this.three.scene, camera);
this.configuration.compose.addPass(renderPass);
this.configuration.compose.addPass(new EffectPass(camera, new BloomEffect()));
```

My render method :
```js
var clock = new ThreeClock();
var delta = clock.getDelta();
this.configuration.compose.render(delta);
```

I'm doing something wrong ?

Thank's a lot for your help

**Comment by vanruesc** [comment]
Your code looks fine. The problem probably lies somewhere else. It would be great if you could provide a minimal reproduction of the problem.

**Comment by BaptisteAugment** [comment]
Finaly FIXED ! I have too old version of three.js in my project, sorry for this inconvience.
