### ISSUE TITLE
is typescript support on the roadmap? 

### ISSUE THREAD

**Issue by thewizardwand** [vanruesc/postprocessing#237]
@types/postprocessing@latest' is not in the npm registry.
npm suggested that I ask the author to publish it ~

**Comment by vanruesc** [comment]
Yes, `postprocessing` will transition to TypeScript in the near future. I've been working with TypeScript during the past few months and can see its value now. I've also come to realize that it fills a role that can't be filled by the ECMAScript language alone.

There are still some things I'd like to implement before the switch so I can't give you an ETA but I'd like to finish it this year.

**Comment by thewizardwand** [comment]
Thanks for the quick response, That’s great to hear!

**Comment by vanruesc** [comment]
Closing this since TypeScript is already on my todo-list.
