### ISSUE TITLE
TAA or accumulation-based anti-aliasing

### ISSUE THREAD

**Issue by veryprofessionaldodo** [vanruesc/postprocessing#238]
### Is your feature request related to a problem?

Currently testing using this framework on a three.js project for a company, and despite SMAA providing much cleaner results compared to no AA, there are still quite a few aliasing artifacts.

### Describe the solution you'd like

An implementation of TAA or an approximation of it, similar to Sketchfab's AA solution ([example](https://sketchfab.com/3d-models/balenciaga-triple-s-trainers-5ab93a0dd3034bff8735576ef827addf)).

**Comment by vanruesc** [comment]
Hi,

have you tried tweaking the SMAA settings, especially the [edge detection](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/SMAAEffect.js~SMAAEffect.html#instance-get-edgeDetectionMaterial) [threshold](https://vanruesc.github.io/postprocessing/public/docs/class/src/materials/EdgeDetectionMaterial.js~EdgeDetectionMaterial.html#instance-method-setEdgeDetectionThreshold)? The newly added [predication mode](https://vanruesc.github.io/postprocessing/public/docs/class/src/materials/EdgeDetectionMaterial.js~EdgeDetectionMaterial.html#instance-method-setPredicationMode) can also improve results depending on the scene. I personally don't think that TAA is a particularly great technique as it produces blurry results and removes a lot of details:

https://images.nvidia.com/geforce-com/international/comparisons/shadow-of-the-tomb-raider/shadow-of-the-tomb-raider-anti-aliasing-interactive-comparison-001-taa-vs-smaa.html (Pay attention to the roof in the background)

**Comment by veryprofessionaldodo** [comment]
First of all, thank you for the speedy reply! 

Interesting, I'll test out different settings, and see what produces the best results. Thanks once again!

**Comment by veryprofessionaldodo** [comment]
After testing, I think we got some great results :) Some aliasing artifacts were actually caused by an error in the maps on my end, thanks once again!

**Comment by vanruesc** [comment]
Cool, glad I could help!
