### ISSUE TITLE
Rendering multiple scenes

### ISSUE THREAD

**Issue by thibka** [vanruesc/postprocessing#239]
Hi,

I must be missing something, but I can't display two scenes at the same time.
The second scene is visible, but no the first one.
I did set the `clear` attribute of the second scene renderPass to `false` though.

```javascript
this.renderPass = new RenderPass(scene, camera);
this.renderPass2 = new RenderPass(scene2, camera);
this.renderPass2.clear = false;

this.composer.addPass(this.renderPass);
this.composer.addPass(this.renderPass2);
```

Here's a sandbox demo: https://codesandbox.io/s/tender-cloud-s4dw2?fontsize=14&hidenavigation=1&theme=dark

What am I missing?

**Comment by vanruesc** [comment]
Your first pass renders to an internal frame buffer while your second pass renders to screen. Depending on what you wish to do, you can let both passes render to the same target, such as the screen, like so:

```js
renderPass.renderToScreen = true;
renderPass2.renderToScreen = true;
```
