### ISSUE TITLE
Updating layer based UnrealBloom to BloomEffect 

### ISSUE THREAD

**Issue by mokargas** [vanruesc/postprocessing#240]
I've been struggling a little bit with this library. I decided to update to it because I found the bloom effects to be more pleasing (and more configurable) than UnrealBloomPass. Especially the `luminancePass`

My problem is, I don't want to head down the route of SelectiveBloomEffect, because I don't want to keep track of selections (or lights)  due to the complexity of the project and mutation of those items over runtime. Each mesh in my project already sets its material to black or otherwise based on layers.

So typically when doing a 'selective' bloom, I use layers like so (this is using `react-three-fiber` and React, but it's generally the same anywhere):

```javascript
function Effects() {
  const { gl, scene, camera, size, viewport } = useThree()
  const aspect = useMemo(() => new THREE.Vector2(256, 256), [])

  const bloomComposer2 = useMemo(() => new EffectComposer(gl), [])
  const finalComposer2 = useMemo(() => new EffectComposer(gl), [])
  bloomComposer2.setSize(size.width, size.height)
  finalComposer2.setSize(size.width, size.height)

  const bloomPass = new UnrealBloomPass(aspect, 2, 0, 0)

  const renderPass = new RenderPass(scene, camera)
  bloomComposer2.renderToScreen = false
  bloomComposer2.addPass(renderPass)
  bloomComposer2.addPass(bloomPass)

  const FinalPassShader = useMemo(
    () => ({
      uniforms: {
        baseTexture: { value: null },
        bloomTexture: { value: null }
      },
      vertexShader: `
    varying vec2 vUv;

			void main() {

				vUv = uv;

				gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );

			}`,
      fragmentShader: `	uniform sampler2D baseTexture;
    uniform sampler2D bloomTexture;

    varying vec2 vUv;

    void main() {

      gl_FragColor = ( texture2D( baseTexture, vUv ) + vec4( 1.0 ) * texture2D( bloomTexture, vUv ) );

    }`,
      defines: {}
    }),
    []
  )

  const finalPass = new ShaderPass(
    new THREE.ShaderMaterial({
      uniforms: {
        baseTexture: { value: null },
        bloomTexture: { value: bloomComposer2.renderTarget2.texture }
      },
      vertexShader: FinalPassShader.vertexShader,
      fragmentShader: FinalPassShader.fragmentShader,
      defines: {}
    }),
    'baseTexture'
  )
  finalPass.needsSwap = true
  finalComposer2.addPass(renderPass)
  finalComposer2.addPass(finalPass)

  useFrame(() => {
    camera.layers.set(GLOW_LAYER)
    bloomComposer2.render()

    camera.layers.set(DEFAULT_LAYER)
    finalComposer2.render()
  }, 1)

  return (
    <>
      <primitive object={bloomComposer2} />
      <primitive object={finalComposer2} />
    </>
  )
}
export default Effects
```

I've tried to replicate this approach in `postprocessing` but without much success:

```javascript
import { BlendFunction, BloomEffect, EffectComposer, EffectPass, KernelSize, RenderPass, ShaderPass} from 'postprocessing'
import React, { useMemo } from 'react'
import { useFrame, useThree } from 'react-three-fiber'
import * as THREE from 'three'
import { Clock } from 'three'
import { DEFAULT_LAYER, GLOW_LAYER } from './static'

function Effects() {
  const { gl, scene, camera, size } = useThree()
  const clock = new Clock()

  const bloomComposer2 = useMemo(() => new EffectComposer(gl), [])
  const finalComposer2 = useMemo(() => new EffectComposer(gl), [])
  bloomComposer2.setSize(size.width, size.height)
  finalComposer2.setSize(size.width, size.height)

  const bloomOptions = {
    blendFunction: BlendFunction.ADD,
    kernelSize: KernelSize.LARGE,
    luminanceThreshold: 0.8,
    luminanceSmoothing: 0.075,
    height: 480,
    threshold: 0.8,
    intensity: 1.4
  }

  const renderPass = new RenderPass(scene, camera)

  const bloomEffect = new SelectiveBloomEffect(scene, camera, bloomOptions)
  const bloomPass = new EffectPass(camera, bloomEffect)

  bloomComposer2.renderToScreen = false
  bloomComposer2.addPass(renderPass)
  bloomComposer2.addPass(bloomPass)

   finalComposer2.renderToScreen = true
   finalComposer2.addPass(renderPass)
// -- finalPass omitted, same as above) except with the renderTarget.texture set to bloomComposer2.outputBuffer.texture
  finalComposer2.addPass(finalPass)

  useFrame(() => {
     camera.layers.set(GLOW_LAYER)
     bloomComposer2.render(clock.getDelta())

     camera.layers.set(DEFAULT_LAYER)
     finalComposer2.render(clock.getDelta())
  
  }, 1)

  return (
    <>
      <primitive object={bloomComposer2} />
      <primitive object={finalComposer2} />
    </>
  )
}
export default Effects
```

Depending on configuration of the pass order, I either have entire scene bloomed, or nothing at all. I have also tried setting the camera layers with a `LambdaPass` and single composer based on another example.

Is it possible to simply render the `BloomEffect` for meshes on layers, then append to a normal renderPass with `postprocessing`?

**Comment by vanruesc** [comment]
Hi,

if you'd like to manage layers yourself, you can do something like this: https://codesandbox.io/s/pedantic-framework-5f4cx?file=/src/App.js

This solution corresponds to your first example. Note, however, that you won't get correct occlusions with this setup because you only render objects that are on the bloom layer:

<img src="https://user-images.githubusercontent.com/9214917/99922990-bd73d880-2d33-11eb-992a-410d213cd110.jpg" width="350">

The `SelectiveBloomEffect` handles proper occlusions, but it's not very efficient at the moment. I'd like to improve its performance in the future - I think I can make it much faster by using depth-based masking - but I haven't gotten around to it yet. This would also eliminate the need to change layers of lights.

> I don't want to keep track of selections (or lights)

I can't tell from your code examples how you manage your render layers, but if you set the layers of the `camera` to a specific one, then your lit objects will appear black unless you also enable that layer for the relevant lights.

**Comment by mokargas** [comment]
@vanruesc 
![image](https://user-images.githubusercontent.com/236984/100161223-1e9ed600-2f05-11eb-88d9-7143e870882a.png)

Actually given the light touch for bloom effects in this project, the first approach is enough (I don't need high accuracy on the occlusions) and it renders super smoothly. Thanks for the example, it helped me pinpoint where I went wrong using the LambdaPass. 

I'll keep an excited eye on `SelectiveBloomEffect` though for other projects :)

**Comment by vanruesc** [comment]
👍

**Comment by FractalHQ** [comment]
I'm on a similar mission, but all of the solutions seem to be in the form of codesandbox examples linked across various threads, all of which fail to load with a very strange error message 😕
