### ISSUE TITLE
 MacOSX/iOSX Safari - ERROR: 0:277: 'GL_OES_standard_derivatives' : extension is disabled

### ISSUE THREAD

**Issue by DonPedroo** [vanruesc/postprocessing#242]
### Description of the bug

on safari browser if custom effect used, shader error appears

### To Reproduce

create any custom effect, open page in safari will see black screen with error. happens only with custom effects !!!

### Expected behavior

in the past, on previous versions of safari browser or earlier versions of three/postprocessing library everything was fine

### Screenshots

[Error] WebGL: ERROR: 0:277: 'GL_OES_standard_derivatives' : extension is disabled
	compileShader
	WebGLShader (app.c3f9f951.js:12868)
	WebGLProgram (app.c3f9f951.js:13194)
	acquireProgram (app.c3f9f951.js:13535)
	initMaterial (app.c3f9f951.js:18150)
	setProgram (app.c3f9f951.js:18234)
	(anonymous function) (app.c3f9f951.js:17764)
	renderObject (app.c3f9f951.js:18110)
	renderObjects (app.c3f9f951.js:18093)
	(anonymous function) (app.c3f9f951.js:17970)
	render (app.c3f9f951.js:40882)
	render (app.c3f9f951.js:41838)
	render (app.c3f9f951.js:51968)
	Sketch (app.c3f9f951.js:51775)
	(anonymous function) (app.c3f9f951.js:51976)
	newRequire (app.c3f9f951.js:47)
	(anonymous function) (app.c3f9f951.js:81)
	Global Code (app.c3f9f951.js:120)

### Library versions used

 - Three: [0.122.0]
 - Post Processing: [6.18.0]

### Desktop

 - Device: [Macbook Pro]
 - OS: [Mac osx Catalina, 10,15,7 ]
 - Browser [Safari  14.0.1 ]

### Mobile

 - Device: [Iphone any]
 - OS: [latest iOS ]
 - Browser [latest safari]

**Comment by vanruesc** [comment]
Does your custom effect use `dFdx`, `dFdy` or `fwidth` in its shader? Are you making sure that [derivatives are enabled](https://github.com/vanruesc/postprocessing/wiki/Custom-Effects#webgl-extensions)?

Please provide a reproduction of the issue. I don't have access to Safari, so I can't test your reproduction steps, but I can look at code.

**Comment by DonPedroo** [comment]
Sorry about that, it was a matter of enabling extensions. It is working now,  Thank you!

**Comment by Hoodgail** [comment]
How was this issue solved? @DonPedroo @vanruesc 
![image](https://user-images.githubusercontent.com/45743294/198831208-a422a92c-0153-4ad4-bc55-39f6fcfc17a6.png)

**Comment by vanruesc** [comment]
@Hoodgail Extensions must be enabled like this:

```js
import { Effect, WebGLExtension } from "postprocessing";

class MyEffect extends Effect {

	constructor() {

		super(name, fragmentShader, {
			extensions: new Set([WebGLExtension.DERIVATIVES])
		});

	}

}
```
