### ISSUE TITLE
Apply effect to one out of multiple render passes

### ISSUE THREAD

**Issue by thibka** [vanruesc/postprocessing#244]
I feel like this a pretty simple question, but I can't find a solution.
I want to be able to apply a specific effect pass to a specific render pass, without affecting other previously drawn render passes.
Something along these lines:
```javascript
composer.addPass(renderPass); // my main scene 
composer.addPass(effectPass); // my main effect pass (SMAA + Vignette for instance)

composer.addPass(renderPass2); // an isolated object on which I want to use a Bloom Effect
composer.addPass(effectPass2); // Bloom Effect
```
Here the bloom effect (effectPass2) will of course affect both render passes. 
How can I apply it on renderPass2 only?

Here is a simplified sandbox example base on this snippet: 
https://codesandbox.io/s/prod-water-5vtns?file=/src/App.js:2664-2758

**Comment by vanruesc** [comment]
Hey, sorry for the late response!

You can render bloom for one scene and then apply the generated bloom texture later using a `TextureEffect`. Here's an example: https://codesandbox.io/s/deferred-bloom-bnwny?file=/src/App.js

This comment might also be relevant: https://github.com/vanruesc/postprocessing/issues/240#issuecomment-731889894 (the part about occlusions).

**Comment by thibka** [comment]
Got it, thank you @vanruesc! 🙏
