### ISSUE TITLE
WebGLRenderer: .getClearColor() now requires a Color as an argument

### ISSUE THREAD

**Issue by MarioAda** [vanruesc/postprocessing#246]
### Description of the bug

This warning keeps pops up in the browser console on every requestAnimationFrame when using GodRaysEffect:
`WebGLRenderer: .getClearColor() now requires a Color as an argument`

### To Reproduce

Simply use GodRaysEffect with the latest version of ThreeJs and you'll get the warning.
As the error states, "getClearColor" now requires a Color as an argument: https://threejs.org/docs/#api/en/renderers/WebGLRenderer.getClearColor

### Screenshots

![image](https://user-images.githubusercontent.com/34167299/103160954-e9c3be80-47e3-11eb-857c-d2fa6a8052ed.png)

### Library versions used

 - Three: 0.124.0
 - Post Processing: 6.18.0

### Desktop

 - OS: Windows 10
 - Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
 - Graphics hardware: NVIDIA GTX 1060TI

**Comment by vanruesc** [comment]
Hi,

thanks for the report! A fix will be included in the next release.

Please note that `postprocessing@6.18.0` officially supports `three ≥ 0.102.0 < 0.123.0` and that such warnings are quite common when a newer version of `three` is used.
