### ISSUE TITLE
missleading removePass behaviour

### ISSUE THREAD

**Issue by fPrager** [vanruesc/postprocessing#254]
### Description of the bug

If you call EffectComposer.removePass( PassXY ) it removes that pass (correct) or the last pass, if the given one is not within the composer (missleading).

Scenario A:

Composer.Passes = [ Pass1, Pass2, Pass3 ]
Composer.removePass( Pass2 )
Composer.Passes = [ Pass1, Pass3 ]

Scenario B:

Composer.Passes = [ Pass1, Pass2, Pass3 ]
Composer.removePass( Pass**4** )
Composer.Passes = [ Pass1, Pass2 ]

### To Reproduce

 * Setup a composer
 * Setup a RenderPass
 * Setup an EffectPass
 * Call Composer.addPass(RenderPass)
 * Call Composer.removePass(EffectPass)

Composer has no passes.

### Expected behavior

It should do nothing, if the given pass is not in the Composer.

### Library versions used

 - Three: [e.g. 0.119.0]
 - Post Processing: [e.g. 6.0.0]

**Comment by fPrager** [comment]
Easy fix would be within the src/EffectComposer.js, line 461:

`
removePass(pass) {

		const passes = this.passes;
		const index = passes.indexOf(pass);
		// line 461 - add the existing check:
		if( index < 0 ) return;

		const removed = (passes.splice(index, 1).length > 0);

		if(removed) {

			if(this.depthTexture !== null) {

`

**Comment by vanruesc** [comment]
Thanks for the report! A fix is underway.

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.19.3`.
