### ISSUE TITLE
SelectiveBloomEffect effecting other objects

### ISSUE THREAD

**Issue by ranbuch** [vanruesc/postprocessing#255]
After defining the `selectiveBloomEffect.selection.set(selection)` with an array on objects the bloom effect does work only on the selected objects (as expected).

It is however changing the way other objects looks like (the `selection` has a single mesh - the rubbery cloth strap):

![image](https://user-images.githubusercontent.com/3777546/104848018-bc9e9380-58eb-11eb-94bd-de34794b78dc.png)

This is how the model looks like without the SelectiveBloomEffect postprocessing:

![image](https://user-images.githubusercontent.com/3777546/104848052-dfc94300-58eb-11eb-850c-295675dad31b.png)

This is how it looks like whene I'n using the SelectiveBloomEffect on the plastic cups mesh, you can see that the bloom effect does work for the lights:

![image](https://user-images.githubusercontent.com/3777546/104848170-71d14b80-58ec-11eb-8a7f-68f850f21f37.png)

Whene using postprocessing you can see artifacts and bad antialiasing.

Those are my bloom options params:
```javascript
const bloomOptions = {
    blendFunction: BlendFunction.SCREEN,
    kernelSize: KernelSize.MEDIUM,
    luminanceThreshold: 0.1,
    luminanceSmoothing: 0.075,
    height: 360
};
```

Anything I can do about it?

Thanks!

 - Three: 0.120.0
 - Post Processing: 6.19.3

### Desktop

 - OS: Windows 10
 - Browser Chrome 87.0.4280.141
 - Graphics hardware: NVIDIA GTX 2060

**Comment by vanruesc** [comment]
Hi,

it looks like you're converting colors to sRGB at the end of your pipeline which causes banding. There also doesn't seem to be any antialiasing going on. See [this](https://github.com/vanruesc/postprocessing#output-encoding) and [this](https://github.com/vanruesc/postprocessing/wiki/Antialiasing) for details. If this information doesn't help, please provide a minimal reproduction of the issue. You can use the [sandbox](https://codesandbox.io/s/postprocessing-25rts) as a starting point.

**Comment by ranbuch** [comment]
@vanruesc Thanks.

The `frameBufferType: HalfFloatType` did solve the artifacts issue.

With regards to the antialiasing, I have tried to utilize the `SMAAEffect` but it seems it's not working when using `OffscreenCanvas` because it's using `Canvas` and `Image` native objects.

Can I just save the `smaa-search` and `smaa-area` images and load them from my CDN or is there a reason that they are being dynamically created on the client?

**Comment by ranbuch** [comment]
@vanruesc Thanks.

I was able to utilize the `SMAAImageLoader` from outside the worker.

However I still can't get results as smooth as I can without the SelectiveBloomEffect.

This is a part of the model with the effect:
![image](https://user-images.githubusercontent.com/3777546/104926942-7ad42280-59a9-11eb-9007-e35cbb096f83.png)

And this is without:
![image](https://user-images.githubusercontent.com/3777546/104927048-a0f9c280-59a9-11eb-86e3-3f10b114ffc2.png)

After setting the edge detection threshold to 0.0001 (`smaaEffect.edgeDetectionMaterial.setEdgeDetectionThreshold(0.0001);`):
![image](https://user-images.githubusercontent.com/3777546/104929135-2da58000-59ac-11eb-91ba-5a4ba8d1779c.png)

Setting it even lower had no effect.

I have no errors on warnings and the effect looks good.

Here is the [model](https://cdn.hexa3d.io/models/headset.glb) I'm using.

**Comment by vanruesc** [comment]
SMAA has many options that can be tweaked to improve results, but if you're not satisfied with SMAA and your environment supports WebGL 2, you can instead use MSAA with SMAA as a fallback. Here's a complete example: https://codesandbox.io/s/inspiring-noether-gdz03?file=/src/App.js

**Comment by ranbuch** [comment]
@vanruesc that's perfect!
Thanks.
