### ISSUE TITLE
Examples: provide simpler usage examples

### ISSUE THREAD

**Issue by marcofugaro** [vanruesc/postprocessing#258]
### Is your feature request related to a problem?

Right now, the examples are too elaborate code-wise. If a new user wants to see the usage of a particular effect to use it in its project, there is too much cognitive load.

Take the SMAA demo for example, there is too much noise you need to filter through in the demo to copy it and use it in your project: you need to know about the SMAAImageLoader, you need to know if the `edgesTextureEffect` or `weightsTextureEffect` are really needed, you need to know what are the `setPredicationMode`, `setPredicationThreshold`, `setEdgeDetectionThreshold` options.

https://github.com/vanruesc/postprocessing/blob/71cffb8ebd7046c097bd096ad8addf5ee8599ab5/demo/src/demos/AntialiasingDemo.js#L195-L239

I get they are needed to make the demo look good, but make the code look much more complicated.

### Describe the solution you'd like

Maybe provide a really basic use-case of the effect via the [JSDoc @example tag](https://jsdoc.app/tags-example.html) and make them show in the Documentation website.

Here is an example usage of the tag in the cannon-es repo:

https://raw.githack.com/pmndrs/cannon-es/typedoc2/docs/classes/body.html

For the SMAA effect, I imagine a basic usage would look something like this:

```js
new SMAAImageLoader().load(([search, area]) => {
  const smaaEffect = new SMAAEffect(search, area)
  composer.addPass(new EffectPass(camera, smaaEffect))
})
```

**Comment by vanruesc** [comment]
> Right now, the examples are too elaborate code-wise.

I'd argue that it's better to have demos that show everything the effects have to offer instead of simple examples that only scratch the surface. This is also important from a debugging point of view because I need a way to actually test every aspect of all effects.

> you need to know about the `SMAAImageLoader`, you need to know if the `edgesTextureEffect` or `weightsTextureEffect` are really needed, you need to know what are the `setPredicationMode`, `setPredicationThreshold`, `setEdgeDetectionThreshold` options.

Yes, users should know about these things. I can see how the texture effects could be distracting, but I don't know what I should do about that. They are required for debugging.

The [wiki contains an article about antialiasing](https://github.com/vanruesc/postprocessing/wiki/Antialiasing) that shows how to setup SMAA. I've used `@example` tags sparingly in the past but I'll try to add more when I convert the code base to TypeScript.

**Comment by marcofugaro** [comment]
> Yes, users should know about these things. I can see how the texture effects could be distracting, but I don't know what I should do about that. They are required for debugging.

Yeah I agree, they're fine like this. I was proposing to add other examples aimed at first-time users, not debugging. The @example tag would suffice.

>  I've used @example tags sparingly in the past but I'll try to add more when I convert the code base to TypeScript.

Great!

**Comment by vanruesc** [comment]
Alright, I've added this to my backlog and I'm closing this issue since there's no clear stopping point when it comes to adding examples. We can address particularly weak or missing examples when the TypeScript conversion is done.

**Comment by marcofugaro** [comment]
I recently started converting the JSDoc comments in TSDoc ones in https://github.com/pmndrs/cannon-es/pull/54.
There are some quirks to know if you're using [Typedoc](https://typedoc.org/) as a website generator, but you will probably have it easier with [esdoc-typescript-plugin](https://github.com/esdoc/esdoc-plugins/tree/master/esdoc-typescript-plugin).
Anyway ask away if you have any questions when you're doing the switch.
