### ISSUE TITLE
Typo in SMAAImageLoader.js?

### ISSUE THREAD

**Issue by morph3us-net** [vanruesc/postprocessing#261]
In this [file](https://github.com/vanruesc/postprocessing/blob/main/src/loaders/SMAAImageLoader.js), on line 4, could there possibly be a typo? 

import workerProgram from "../../tmp/smaa.worker";

=>

import workerProgram from "../../tmp/smaa/worker";
(So basically a dot instead of a forward slash?)

Maybe this could be elaborated on in the [Wiki](https://github.com/vanruesc/postprocessing/wiki/Antialiasing)?
I am sorry if I misunderstoof the Javascript Voodoo, I am not a professional programmer...

**Comment by morph3us-net** [comment]
Looks like its not:
Uncaught SyntaxError: The requested module '../images/smaa/worker.js' does not provide an export named 'default'

Would be anybody please tell me whats going? 
SMAAImageLoader is importing something from a directory that does not exist?
On first glance it looks like it actually generates that file in the generate functions a few lines below...
And then I dont get why it should put it into that folder specifically, as I dont see where that would be passed into the function?

**Comment by vanruesc** [comment]
Hi!

The build setup creates multiple independent JS-bundles and [two of them use a custom `.worker` file extension](https://github.com/vanruesc/postprocessing/blob/71cffb8ebd7046c097bd096ad8addf5ee8599ab5/esbuild.config.ts#L44-L47). That extension is arbitrary - it could also be `.txt`, for example, but it must not be `.js` because we don't want to import that code as a module. The `SMAAImageLoader` and `LookupTexture3D` import these bundles [as plain text](https://github.com/vanruesc/postprocessing/blob/71cffb8ebd7046c097bd096ad8addf5ee8599ab5/esbuild.config.ts#L34) so that they can be used to [create worker threads from blobs](https://developer.mozilla.org/en-US/docs/Web/API/Worker#constructors) at runtime.

**Comment by morph3us-net** [comment]
Hi vanru! 

Thanks for making this awesome library available for people even like me! I am really awed by what you managed to squeese out of WebGL!

I managed to set up a local Node.js server with npm. I am currently not "building" anything, but threw together the script into a folder and call the whole three.js shebang from a very simple html file.
This has probably next to nothing to do with three.js or post processing, but is a rather basic question of setting up the server?

I'm sorry, this is so overwhelming, didnt know what I leapt into, but would love to pull through...

**Comment by vanruesc** [comment]
I'm glad you like it!

You could try this to get things going:

1. Clone or download the repository, open your terminal/console and navigate to its root directory.
2. Run `npm install` to download dependencies.
3. Build the project and run a dev server with `npm run dev`.
4. Open a browser and go to http://localhost:8080/demo/.

The `npm` tool is part of Node.js. All build scripts are defined in [package.json](https://github.com/vanruesc/postprocessing/blob/71cffb8ebd7046c097bd096ad8addf5ee8599ab5/package.json#L43-L59).

**Comment by morph3us-net** [comment]
I hope you do not mind lending a hand with some broader questions? Please, just tell me if I should go somewhere else for this.

So according to [this](https://developpaper.com/question/the-difference-between-npm-run-dev-and-npm-start/), "npm rund dev" is the same as "npm start"? Because thats what I am using now. (My local address is different, though: http://127.0.0.1:3000)

I start the server up once I start working on the site, do I need to restart the server? Thats not how the tutorials work... :D

Node.js complains about everything thats not ES6. 
(Apart from that, the scene I am using, which I created [here](https://www.vantajs.com/?effect=net#(backgroundAlpha:1,backgroundColor:1774603,color:16746752,gyroControls:!f,maxDistance:29,minHeight:200,minWidth:200,mouseControls:!t,points:3,scale:1,scaleMobile:1,showDots:!t,spacing:20,touchControls:!t)) and downloaded an unminified version of to add DoF to [here](https://github.com/tengbao/vanta/blob/master/src/vanta.net.js), was already ES6 compliant.)

So none of the imports are working (importing the .frag and .vert files will be tricky, too, as only .js files are allowed!) and I am currently trying to somehow get rid of one error message after the other. Thats where I stumbled upon the smaa.worker import, which I until now do not fully understand, I fear...

The thing is, I am not too sure how my online server will react in the end, if I do too much fancy stuff to my offline server, like, if I start Node.js in dev mode, will my site work properly in the end?

**Comment by vanruesc** [comment]
I'm afraid that this question is too broad to be answered in detail. However, it looks like you're trying to create an app that uses the `postprocessing` library in some way. In that case you should install `postprocessing` as a dependency by running `npm install postprocessing --save`. This will download the library into the `node_modules` folder. Note that the installed version differs from the repository version in that it only includes the final bundles. Custom `.frag` or `.worker` imports are already integrated.

You should then be able to import modules from `postprocessing` in you code via `import { Something } from "postprocessing";`

**Comment by morph3us-net** [comment]
Thanks for the input! I got it working, though it was a tad more complicated. The biggest hint was the difference between the repository and the npm download.

For other people who stumble upon this via google, who have as much clue as me:
[This](https://www.youtube.com/watch?v=z9qtGHTqLqQ&lc=UgweHaIn86hokBMspft4AaABAg.9Iu6vp2f55O9IuRihcLKil) tutorial helps with setting up a local server.

Shut down your node.js server (CTRL+C in the windows terminal) and install postprocessing like mentioned above.
Open your app.js and add the line
`app.use('/postprocessing/', express.static(path.join(__dirname, 'node_modules/postprocessing/build')));`
This relinks all imports in your javascript files to the appropriate node.

Open the postprocessing.esm.js in the "node_modules\postprocessing\build" folder and replace "three" with "/build/three.module.js"

Now you can import via:
`import { Something } from "/postprocessing/postprocessing.esm.js";`

Now you can start your server again and everything should work fine.

(The only thing I'm still wondering about is how one would package that local stuff up and deploy it onto an Apache server, as thats where the target website sits on. Would you have a hint on that? Is there a program you could recommend?)

I am closing this, thank you again for your generous help! Its not easy to focus on the problem when you have a million unanswered questions buzzing around, so, sorry for any dumb questions!

Grüße ausm Berliner Speckgürtel! :)

**Comment by vanruesc** [comment]
> I havent gotten that far, but I believe in the end I will need something as Webpack to package the app for online use on an Apache Server?

Yes, you should use a bundler like [esbuild](https://github.com/evanw/esbuild), [swc](https://github.com/swc-project/swc), [rollup](https://github.com/rollup/rollup), [webpack](https://github.com/webpack/webpack) or [parcel](https://parceljs.org/) depending on your preferences.

Note that a server is only required to properly serve your static assets, including JS bundles and HTML files. You could write a JS-app, include it in a simple HTML file and run it from disk without a server. However, most asset loaders for textures, models, etc. use AJAX requests and those don't work without a server. It's therefore common practice to run a simple local dev server for advanced testing setups that involve asset loading.
