### ISSUE TITLE
I present you the live shader editor compatible with postprocessing

### ISSUE THREAD

**Issue by RenaudRohlinger** [vanruesc/postprocessing#272]
Hello! Thanks for this amazing library.
This is not an issue but a new tool that could be useful.

I made a live shader editor that automatically detects all the passes of your postprocessing library so you can easily test/update the shaders. It handles errors and more. I hope it can be useful to anyone using the postprocessing.

![image](https://user-images.githubusercontent.com/15867665/108365294-64381a00-723a-11eb-8d94-c3dc357567fc.png)

Repo:
https://github.com/RenaudRohlinger/three-material-editor

Demo with postprocessing:
https://pb3d1.csb.app/

Demo source:
https://codesandbox.io/s/kind-khayyam-pb3d1?file=/src/index.js

**Comment by vanruesc** [comment]
That looks nice, thanks for sharing 👌

**Comment by RenaudRohlinger** [comment]
Thanks! I am working on the next version there will be an interface for the uniforms.

**Comment by RenaudRohlinger** [comment]
@vanruesc version v0.3.0. has been released! It's still very WIP but automatic uniforms works. It even handles dynamic textures:
https://pb3d1.csb.app/

**Comment by vanruesc** [comment]
I've created a new [Wiki page for community plugins and tools](https://github.com/vanruesc/postprocessing/wiki/Plugins-%26-Tools) and added `three-material-editor` to the list. Let me know if I should change anything about the entry.
