### ISSUE TITLE
Trying to use SMAA with other THREEjs passes in Angular

### ISSUE THREAD

**Issue by Fluqz** [vanruesc/postprocessing#273]
Hey, thanks for that great lib! 
Im trying to use your SMAA Pass, but im already failing on implementing your code in my Angluar project. Its missing the types. Would be great to have these as well.

Also I had another issue, i replaced the THREE.EffectComposer and RenderPass with the one from your lib and got some errors when using other passes from threejs.

            this.composer.addPass(this.renderPass) // Postprosessing lib pass
            this.composer.addPass(this.outline) // THREEjs pass <--- Error
            this.composer.addPass(this.gammaCorrection)
            this.composer.addPass(this.FXAA)

```
TypeError: pass.initialize is not a function. (In 'pass.initialize(renderer, alpha, frameBufferType)', 'pass.initialize' is undefined)
addPass — postprocessing.esm.js:2552
```

Sincerely

**Comment by vanruesc** [comment]
> i replaced the THREE.EffectComposer and RenderPass with the one from your lib and got some errors when using other passes from threejs.

This library is not compatible with three's post processing examples.

> Its missing the types. 

A conversion to TypeScript is on my todo list.
