### ISSUE TITLE
[Question] Confused about clipW in ssao fragment shader

### ISSUE THREAD

**Issue by scarletsky** [vanruesc/postprocessing#275]
Hi, I am learning ssao from your excellent library. But I am confused about your `clipW` calculation. Here is the snippet from  [ssao/shader.frag](https://github.com/vanruesc/postprocessing/blob/main/src/materials/glsl/ssao/shader.frag#L70):

```glsl
vec3 getViewPosition(const in vec2 screenPosition, const in float depth, const in float viewZ) {
	float clipW = projectionMatrix[2][3] * viewZ + projectionMatrix[3][3];
	vec4 clipPosition = vec4((vec3(screenPosition, depth) - 0.5) * 2.0, 1.0);
	clipPosition *= clipW; // Unproject.

	return (inverseProjectionMatrix * clipPosition).xyz;
}
```

The `clipW` is calculated by `Az+B`. But in [OpenGL Projection Matrix](http://www.songho.ca/opengl/gl_projectionmatrix.html), the projection matrix is:

![](http://www.songho.ca/opengl/files/gl_projectionmatrix_eq10.png)

The `Az+B` should be `clipZ` not `clipW` and the `clipW` should be `-z`.

What is the magic in your code ?

Thanks.

**Comment by vanruesc** [comment]
The `getViewPosition` function comes from the original [SAOPass](https://github.com/mrdoob/three.js/blob/6f86fda4d312996e3f4281ceccc02f0419e55c0d/examples/js/shaders/SAOShader.js#L99-L105) which probably copied it from the [SSAOPass](https://github.com/mrdoob/three.js/blob/6f86fda4d312996e3f4281ceccc02f0419e55c0d/examples/js/shaders/SSAOShader.js#L107-L117). I didn't come up with the math, but I agree that it seems a bit strange.

WebGL uses column-major matrices, so `projectionMatrix[2][3]` is actually `-1.0` and `projectionMatrix[3][3]` is `0.0`, so `clipW` is `-viewZ`. This code probably wasn't fully optimized although it seems to be an optimized version of the following:

```glsl
vec4 clipPosition = vec4(vec3(screenPosition, depth) * 2.0 - 1.0, 1.0);
vec4 viewPosition = inverseProjectionMatrix * clipPosition;
viewPosition /= viewPosition.w; // Unproject (division uses more cycles).
```
[Source](https://github.com/McNopper/OpenGL/blob/a5569db74397cc6531b63bc57c52dfdbf3253e68/Example28/shader/ssao.frag.glsl#L30-L47)

**Comment by vanruesc** [comment]
> This code probably wasn't fully optimized

On second thought, I think this calculation is necessary to support both perspective as well as orthographic projection:

![](http://www.songho.ca/opengl/files/gl_projectionmatrix_eq24.png)

With this orthographic projection matrix, `projectionMatrix[2][3]` would be `0.0` and `projectionMatrix[3][3]` would be `1.0`. So `clipW` would be `1.0` in this case.

**Comment by scarletsky** [comment]
Oh, I see. It is my mistake to get the wrong index of the projection matrix. 😅 

```glsl
vec4 clipPosition = vec4(vec3(screenPosition, depth) * 2.0 - 1.0, 1.0);
```

But this is not `clipPosition`, it is `ndcPosition` right ?

```glsl
// As ndcPosition = clipPosition / clipPosition.w
vec4 clipPosition = ndcPosition * clipW;
vec4 viewPosition = inverseProjectionMatrix * clipPosition;
```

**Comment by scarletsky** [comment]
Oh, I see. It is my mistake to get the wrong index of the projection matrix. 😅
