### ISSUE TITLE
toneMapping overexpose the scene

### ISSUE THREAD

**Issue by MrMateo7** [vanruesc/postprocessing#284]
### Description of the bug

Add `ToneMappingEffect` and set a different one than the default overexposes the scene.

### To Reproduce

This is my code.
```
import {
    EffectComposer,
    RenderPass,
    EffectPass,
    BlendFunction,
    ToneMappingEffect, ToneMappingMode,
    BloomEffect, KernelSize,
    NoiseEffect,
    SMAAImageLoader, SMAAEffect,
} from './build/postprocessing.esm.js';

...

const renderPass = new RenderPass(scene, camera)

    const smaaImageLoader = new SMAAImageLoader()
    let smaaEffect
    smaaImageLoader.load( (e) => {
        smaaEffect = new SMAAEffect( e[0], e[1])
        smaaEffect.edgeDetectionMaterial.setEdgeDetectionThreshold(0.05)
        const smaaPass = new EffectPass( camera, smaaEffect )
        composer.addPass( smaaPass )
    } )

    const noiseEffect = new NoiseEffect({ premultiply: true })
    noiseEffect.blendMode.opacity.value = .45
    
    const bloomEffect = new BloomEffect({
        intensity: 1,
        luminanceThreshold: 0.8,
        luminanceSmoothing: 0.125,
        kernelSize: KernelSize.HUGE,
    })

    const toneMappingEffect = new ToneMappingEffect()
    toneMappingEffect.blendFunction = BlendFunction.SKIP
    toneMappingEffect.mode = ToneMappingMode.ACES_FILMIC

    const ePass = new EffectPass( camera, noiseEffect, bloomEffect, toneMappingEffect )    

    composer = new EffectComposer(renderer, {
        frameBufferType: THREE.HalfFloatType
    })
    composer.addPass( renderPass )
    composer.addPass( ePass )
```

This renders
![image](https://user-images.githubusercontent.com/80969412/114246242-bef71380-9957-11eb-85d4-f0a4c65b489b.png)

but when I remove `toneMappingEffect` from `ePass`
![image](https://user-images.githubusercontent.com/80969412/114246302-e1892c80-9957-11eb-8c6c-1cbe9fac0227.png)

Even when it has `toneMappingEffect.blendFunction = BlendFunction.SKIP`

### Expected behavior

Shows correctly `toneMappingMode`

### Screenshots

Attached in descrption.

### Library versions used

 - Three: R124
 - Post Processing: 6.21.3

### Desktop

 - OS: Windows 10
 - Browser Chrome 89.0.4389.114
 - Graphics hardware: NVIDIA Quadro K2100M

### Mobile

 - OS: [e.g. Android 10]
 - Browser [e.g. Firefox 68.11.0]

**Comment by vanruesc** [comment]
`ToneMappingEffect.mode` is a private field. Try replacing `toneMappingEffect.mode = ToneMappingMode.ACES_FILMIC` with `toneMappingEffect.setMode(ToneMappingMode.ACES_FILMIC)`.

Also, are there any errors or warnings in the console?

**Comment by vanruesc** [comment]
`ToneMappingEffect.blendFunction` also doesn't exist. Please use `toneMappingEffect.blendMode.setBlendFunction(BlendFunction.SKIP)` instead.

**Comment by MrMateo7** [comment]
Any errors.
And as you write, in that way it works fine! 

Thanks master.

**Comment by vanruesc** [comment]
> how can I know wich fields are private or public?

The [documentation](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/blending/BlendMode.js~BlendMode.html) shows only public and protected class members. There are also plans to convert this project to TypeScript which will make it easier to navigate the public API via code completion in IDEs like VSCode.
