### ISSUE TITLE
Getting world position from vertex shader

### ISSUE THREAD

**Issue by risq** [vanruesc/postprocessing#285]
Hello,

I'm trying to implement a custom pass in a postprocessing pipeline, but I can't find a way to get the world positions of my scene.

I use this very simple shader as a base, which works on threejs default composer : https://jsfiddle.net/4nzkwesg/1/

**vert :**
```vert
    varying vec3 vColor;

    void main()
    {
        vec4 worldPosition = modelMatrix * vec4(position, 1.0);
        vColor = normalize(abs(worldPosition.xyz));
        gl_Position = projectionMatrix * viewMatrix * worldPosition;
    }
```

**frag :**
```frag
    precision mediump float;

    varying vec3 vColor;

    void main()
    {
        gl_FragColor = vec4(vColor, 1.0);
    }
```

But I can't make it work on postprocessing because (it seems) I get screen space positions : 
<img width="1043" alt="Screenshot 2021-04-13 at 15 00 26" src="https://user-images.githubusercontent.com/5665322/114556442-00920200-9c69-11eb-91ff-37489cfa992f.png">

I'm calling this pass just after the renderPass.

What would be the correct way to port this shader to postprocessing ? Should I pass the geometries as attributes somewhere ? Or is there another way to access it from the vertex shader ?

Thank you very much.

**Comment by risq** [comment]
Sorry, what I want is not something I can achieve in standard three.js composer, it only works for a mesh material but not in a post processing screen space shader, which makes sense.

I still don't know if this is possible but I'll close this issue as this is not linked to this library.

**Comment by vanruesc** [comment]
Rendering world positions requires rendering geometry/meshes. As you've already pointed out, this can't be done in a fullscreen pass because the shader would only render the world position of the fullscreen triangle fragments.

To render world positions of objects, you'll need to use a [RenderPass](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/RenderPass.js~RenderPass.html#instance-constructor-constructor) with an override material. For reference, take a look at the [DepthPass](https://github.com/vanruesc/postprocessing/blob/main/src/passes/DepthPass.js) and the [NormalPass](https://github.com/vanruesc/postprocessing/blob/main/src/passes/NormalPass.js).

Here's an example implementation: https://codesandbox.io/s/clever-hooks-okxv0?file=/src/MeshWorldPositionMaterial.js

**Comment by risq** [comment]
Thank you very much ! It helps a lot !

I just came across a problem which seems to be also linked to the world and screen spaces :
I would like to mix my render input buffer to the world position pass (the goal of this shader is to fade pixels to black when they reach a Y threshold, like a world space fog).

Following your wiki, I added an inputBuffer uniform I passed to the WorldSpaceMaterial. The next step would be to draw the buffer in the FragColor, and mix the pixel color with black, depending on the world position Y. The problem (I think) is that as the vertex are set in world space in the vertex shader, the input buffer is not drawn in screen space anymore but in world space : 

<img width="292" alt="Screenshot 2021-04-14 at 13 00 41" src="https://user-images.githubusercontent.com/5665322/114700169-75c10e00-9d21-11eb-929b-e15e55697310.png">

Do you know if it is possible to "unproject" it so I can just get the current pixel from the buffer and mix it directly with my world Y value ?
(here is my sandbox : https://codesandbox.io/s/beautiful-firefly-bt0uo?file=/src/MeshWorldPositionMaterial.js)

Thank you again for your time.

**Comment by vanruesc** [comment]
For that you'd make an Effect. For example: https://codesandbox.io/s/gallant-dew-9zog6?runonclick=1&file=/src/FogEffect.js

The strategy is this: render the scene colors (RenderPass) and the world position (WorldPositionPass) data into two separate buffers and then use those buffers in a fullscreen shader to render the desired effect. The scene colors are already available to Effect shaders via the `inputColor` argument.

An optimal pipeline would make use of multiple render targets (MRT) to render the geometry buffers but three.js doesn't support that yet.

**Comment by risq** [comment]
Thank you very much, it works perfectly !
I now understand better how the pipeline works and the difference between effects and passes. Blend function seems to be very powerful too !

Thanks again for your time, this is really appreciated :)
