### ISSUE TITLE
Always white background, ¿how make it transparent?

### ISSUE THREAD

**Issue by MrMateo7** [vanruesc/postprocessing#286]
### Description of the bug

Always getting a white background, but I need to keep the alpha of the renderer.

### To Reproduce

It's a very basic code.
```
const renderer = new window.THREE.WebGLRenderer({
          canvas,
          alpha: true,
          powerPreference: 'high-performance',
          antialias: false,
          stencil: false,
          depth: false,
        })
        renderer.autoClear = false
        renderer.setSize(canvasWidth, canvasHeight)
        renderer.setClearColor(0xffffff, 0)
        renderer.toneMapping = THREE.ACESFilmicToneMapping
        renderer.toneMappingExposure = 0.9
        renderer.physicallyCorrectLights = true

        // Vanrue
        const composer = new EffectComposer(renderer)
        const renderPass = new RenderPass(scene, camera)
        const bloomEffect = new BloomEffect({
          intensity: 1.4,
          luminanceThreshold: 0.6,
          luminanceSmoothing: 0.1,
          kernelSize: KernelSize.SMALL,
        })
        const ePass = new EffectPass(camera, bloomEffect)
        const smaaImageLoader = new SMAAImageLoader()
        smaaImageLoader.load((e) => {
          const smaaEffect = new SMAAEffect(e[0], e[1])
          smaaEffect.edgeDetectionMaterial.setEdgeDetectionThreshold(0.05)
          const smaaPass = new EffectPass(camera, smaaEffect)
          composer.addPass(smaaPass)
        })

        composer.addPass(renderPass)
        // composer.addPass(ePass)
```

### Expected behavior

Keep the alpha of native WebGLRenderer.

### Screenshots

Without.
![WhatsApp Image 2021-04-15 at 12 55 50 PM](https://user-images.githubusercontent.com/80969412/114955905-4a264c80-9e23-11eb-885a-2ad5abe6d66d.jpeg)

With.
![WhatsApp Image 2021-04-15 at 12 55 50 PM (1)](https://user-images.githubusercontent.com/80969412/114955917-50b4c400-9e23-11eb-90f8-f80393538686.jpeg)

### Library versions used

 - Three: R124
 - Post Processing: 6.21.3

### Desktop

Is a mobile AR, not for desktop.

### Mobile

 - Device: Huawei p30
 - OS: Android 10
 - Browser: Chrome 90.0.4430.66

**Comment by vanruesc** [comment]
Using a transparent canvas should work just fine. The following example has `alpha` enabled: https://codesandbox.io/s/sleepy-cloud-1ls0m?runonclick=1&file=/src/App.js

Make sure that you're not using a flat color as your `scene.background` as this can interfere with your clear color. If your app still renders a white background after double checking with the example above, please provide a reproduction of the problem.

Also note that `renderer.toneMapping` applies tone mapping to individual objects during the `RenderPass` which is _not_ desirable for post processing. Instead, you should use the `ToneMappingEffect` on the final image.

**Comment by MrMateo7** [comment]
Watching everythis is due to the platform 8thwall (user for AR apps), wich when you use Post always make white brackground.

Your postprocessing is awesome! Where can I buy you a beer?

**Comment by vanruesc** [comment]
> this is due to the platform 8thwall (user for AR apps)

I see, so this seems to be an issue with an external framework. The documentation of 8th Wall says something about a "Transparent Canvas" checkbox under [Settings -> Rendering](https://www.8thwall.com/docs/web/#getting-started-with-playcanvas). Maybe that has something to do with the white background.

> Where can I buy you a beer?

This link should work: https://www.paypal.com/paypalme/raoulvr 😇

**Comment by MrMateo7** [comment]
> This link should work: https://www.paypal.com/paypalme/raoulvr 😇
Sended, Cheers!

**Comment by MrMateo7** [comment]
> This link should work: https://www.paypal.com/paypalme/raoulvr 😇

Sended, cheers!

**Comment by vanruesc** [comment]
Thanks 😄

**Comment by UMUTBAYGUT** [comment]
@MrMateo7  Why you used new window.THREE.WebGLRenderer instead of 8thWall Renderer?
