### ISSUE TITLE
Using ShaderMaterial with EffectComposer makes objects bright

### ISSUE THREAD

**Issue by olee** [vanruesc/postprocessing#287]
### Description of the bug

When using a ShaderMaterial together with EffectComposer it will make everything affected by the ShaderMaterial somehow brighter.

### To Reproduce

https://codesandbox.io/s/three-postprocessing-issue-4c2wz?file=/src/App.js

When clicking the canvas in this example, it toggles rendering by default or with EffectComposer or not.

I also noticed that removing the EffectPass also solves the issue (kinda obviously...)

### Expected behavior

No matter if EffectComposer is used or not, the color returned from ShaderMaterial shader should not be different (as long as it is not affected by effects of course)

### Screenshots

Here are screenshots from the actual project where I notices this issue where I am rendering a VideoTexture with a ShaderMaterial:

Without EffectComposer:
![image](https://user-images.githubusercontent.com/6547794/115180888-f3e13400-a0d6-11eb-8bd3-a8d8e633956a.png)

With EffectComposer:
![image](https://user-images.githubusercontent.com/6547794/115180903-fd6a9c00-a0d6-11eb-8d86-647a9f5ce163.png)

### Library versions used

 - Three: 0.127.x
 - Post Processing: 6.21.3

**Comment by vanruesc** [comment]
This is a technical question related to color space conversion / gamma correction. The short answer is: it's complicated.

Fullscreen shaders in `postprocessing` convert all pixels to `renderer.outputEncoding` via three's [encoding system](https://github.com/vanruesc/postprocessing/blob/d04698a2e15e47ef6f52bc32610ff44b6939d10e/src/materials/glsl/effect/shader.frag#L78). If you just render objects directly to screen, color encoding will instead be applied to individual objects. The clear color will be treated as-is, meaning that you _don't_ want to convert it into a linear color beforehand. Note that the `EffectComposer` disables `renderer.autoClear`, so if you want to actually see the clear color when the composer is disabled, you'll have to switch that back on as well.

Furthermore, if you want to use a custom material, make sure to take a look at three's [built-in shaders](https://github.com/mrdoob/three.js/tree/dev/src/renderers/shaders/ShaderLib) to know which shader chunks are needed for certain features like color encoding. In this case you'd need to `#include <encodings_fragment>` in your fragment shader.

Example: https://codesandbox.io/s/three-postprocessing-issue-forked-b244h?file=/src/App.js

**Comment by olee** [comment]
Well I added the fragment and now there is no difference anymore between enabled and disabled EffectComposer.
However, the material is still way brighter than the color I set.
I want to use the shader to render a video in the same colors which are actually in the shader.

I'm trying right now to build a shader based on the link to the built-in shaders you sent me, but I don't know yet how to enable the #ifdef sections yet

**Comment by vanruesc** [comment]
> However, the material is still way brighter than the color I set.

You may need to convert your sRGB color to linear to get the desired result on screen:
```js
const colorLinear = colorSRGB.clone().convertSRGBToLinear();
```
Color textures usually have their `encoding` set to `sRGBEncoding`. The built-in materials in `three` use the [mapTexelToLinear](https://github.com/mrdoob/three.js/blob/6df08ab12ec3f568c5371084556018200df35b06/src/renderers/shaders/ShaderChunk/map_fragment.glsl.js#L6) function to decode colors for further calculations. This function is actually [just a macro](https://github.com/mrdoob/three.js/blob/6df08ab12ec3f568c5371084556018200df35b06/src/renderers/webgl/WebGLProgram.js#L650-L654) that resolves to one of the functions defined in [<encodings_pars_fragment>](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/encodings_pars_fragment.glsl.js).

> I want to use the shader to render a video

Rendering a video is not much different from rendering a texture. Just make sure the `encoding` is correct (`sRGBEncoding`) and your shader uses the `mapTexelToLinear` function. No need for any custom shader chunks or #ifdefs (as far as I can tell).

**Comment by olee** [comment]
Yeah when I used the map_fragment chunk which contains this mapTexelToLinear as a basis, it fixed the issues with color.
Thanks for the help
