### ISSUE TITLE
DepthOfFieldEffect can preserve transparency?

### ISSUE THREAD

**Issue by MrMateo7** [vanruesc/postprocessing#288]
### Description of the bug

Hi! again me jajaja
DepthOfFieldEffect makes the background black.

### To Reproduce

```
const renderPass = new RenderPass(scene, camera)

    const smaaImageLoader = new SMAAImageLoader()
    smaaImageLoader.load( (e) => {
        const smaaEffect = new SMAAEffect( e[0], e[1])
        smaaEffect.edgeDetectionMaterial.setEdgeDetectionThreshold(0.05)
        const smaaPass = new EffectPass(camera, smaaEffect)
        // composer.addPass(smaaPass)
    })

    const noiseEffect = new NoiseEffect({ premultiply: true })
    noiseEffect.blendMode.opacity.value = .33
    
    const bloomEffect = new BloomEffect({
        intensity: 0.55,
        luminanceThreshold: 0.8,
        luminanceSmoothing: 0.1,
        kernelSize: KernelSize.VERY_LARGE,
    })

    const toneMappingEffect = new ToneMappingEffect({
        mode: ToneMappingMode.ACES_FILMIC
    })

    const p = {
        focusDistance: 0,
        focalLength: 0.05,
        bokehScale: 5
    }
    gui.add(p, 'focusDistance').min(0).max(1).step(0.05)
    gui.add(p, 'focalLength').min(0).max(1).step(0.05)
    gui.add(p, 'bokehScale').min(0).max(3).step(0.1)

    const dofEffect = new DepthOfFieldEffect( camera, {
        focusDistance: p.focusDistance,
        focalLength: p.focalLength,
        bokehScale: p.bokehScale
    })

    const ePass = new EffectPass( 
        camera,
        dofEffect,
        noiseEffect,
        bloomEffect,
        toneMappingEffect,
    )    

    composer = new EffectComposer(renderer, {
        frameBufferType: THREE.HalfFloatType
    })
    composer.addPass( renderPass )
    composer.addPass( ePass )
```

### Expected behavior

Preserve transparent canvas.

### Screenshots

With
![image](https://user-images.githubusercontent.com/80969412/115652577-21a2c480-a2f3-11eb-91d8-8e6da4647636.png)

Without
![image](https://user-images.githubusercontent.com/80969412/115652626-397a4880-a2f3-11eb-81e4-8c3af13d0f41.png)

### Library versions used

 - Three: 124
 - Post Processing: 6.21.3

### Desktop

 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome 0.0.0.0]
 - Graphics hardware: [e.g. NVIDIA GTX 1050]

### Mobile

 - OS: [e.g. Android 10]
 - Browser [e.g. Firefox 68.11.0]

**Comment by vanruesc** [comment]
Thanks for the report!

This was recently fixed in https://github.com/vanruesc/postprocessing/commit/89569e1bac01eaedab5b26febac8b81279c30385. The fix will be included in the next release. You can use the following code to make it work now:

```js
import { MaskFunction } from "postprocessing";

// @TODO This is a workaround. Remove it in postprocessing 6.21.4.
const maskMaterial = depthOfFieldEffect.maskPass.getFullscreenMaterial();
maskMaterial.maskFunction = MaskFunction.MULTIPLY;
```

Related: https://github.com/vanruesc/postprocessing/issues/226#issuecomment-822537302

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.21.4`.

**Comment by MrMateo7** [comment]
That means I dont need to use a MaskFunction in 6.21.4?

**Comment by vanruesc** [comment]
> That means I dont need to use a MaskFunction in 6.21.4?

Yes, the code I posted [above](https://github.com/vanruesc/postprocessing/issues/288#issuecomment-824652712) was just a temporary workaround.
