### ISSUE TITLE
SMAA bug on tiny geo.

### ISSUE THREAD

**Issue by MrMateo7** [vanruesc/postprocessing#290]
### Description of the bug

On tiny geo shows hard edges and pixels.

### To Reproduce

```
const smaaImageLoader = new SMAAImageLoader()
    smaaImageLoader.load( (e) => {
        const smaaEffect = new SMAAEffect( e[0], e[1])
        smaaEffect.preset = SMAAPreset.ULTRA
        smaaEffect.edgeDetectionMode = EdgeDetectionMode.DEPTH
        smaaEffect.edgeDetectionMaterial.setEdgeDetectionThreshold(0.02)
        const smaaPass = new EffectPass(camera, smaaEffect)
        composer.addPass(smaaPass)
    })
```

### Expected behavior

Not that weird behaviour. Pixels shows awkard like without antialiasing.

### Screenshots

![image](https://user-images.githubusercontent.com/80969412/116270749-fbdb4c80-a744-11eb-8eef-03078510b169.png)

### Library versions used

 - Three: 124
 - Post Processing: 6.21.3

### Desktop

 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome 0.0.0.0]
 - Graphics hardware: [e.g. NVIDIA GTX 1050]

### Mobile

 - OS: [e.g. Android 10]
 - Browser [e.g. Firefox 68.11.0]

**Comment by MrMateo7** [comment]
Is there any way to use another antialiasing system? FXAA or any other?

**Comment by vanruesc** [comment]
Have you tried `EdgeDetectionMode.COLOR`? That should work much better with your scene.

You can also use MSAA, but this feature requires WebGL 2:

```js
const renderer = composer.getRenderer();

if(renderer.capabilities.isWebGL2) {

	const context = renderer.getContext();
	composer.multisampling = Math.min(8, context.getParameter(context.MAX_SAMPLES));

}
```

Alternatively, you could create a custom FXAA effect as shown [in this example](https://codesandbox.io/s/inspiring-borg-4hym0?runonclick=1&file=/src/FXAAEffect.js).

**Comment by vanruesc** [comment]
I just noticed that you're not setting the edge detection mode correctly. Instead of

```js
smaaEffect.preset = SMAAPreset.ULTRA
smaaEffect.edgeDetectionMode = EdgeDetectionMode.DEPTH
```

you should do this:

```js
smaaEffect.applyPreset(SMAAPreset.ULTRA);
smaaEffect.edgeDetectionMaterial.setEdgeDetectionMode(EdgeDetectionMode.DEPTH);
```

**Comment by arpu** [comment]
i had good result for this with https://threejs.org/docs/#api/en/materials/Material.alphaToCoverage on Material side

**Comment by MrMateo7** [comment]
> Have you tried `EdgeDetectionMode.COLOR`? That should work much better with your scene.


> ```js
> smaaEffect.applyPreset(SMAAPreset.ULTRA);
> smaaEffect.edgeDetectionMaterial.setEdgeDetectionMode(EdgeDetectionMode.DEPTH);
> ```

Both gives me the same results as I have actually.
Keep having those hard pixels wich are no present, for example, with antialiasing of renderer (without post).

My "solution" was change the geometry to make thicker this filaments.
![image](https://user-images.githubusercontent.com/80969412/116415806-605ae200-a7ff-11eb-93d2-5d53697b7c75.png)

**Comment by vanruesc** [comment]
> My "solution" was change the geometry to make thicker this filaments.

That's a reasonable solution 👍 

FYI: MSAA has access to more fine-grained depth information and would probably manage to antialias these thin polygons. SMAA, on the other hand, operates at a later stage, so if the input colors are already jumbled and broken, then there's nothing that can be done to bring the information back.
