### ISSUE TITLE
LUT makes scene turns completely black on Samsung Galaxy S7

### ISSUE THREAD

**Issue by Ben-Mack** [vanruesc/postprocessing#298]
Color grading demo on Samsung Galaxy S7 (exynos) using Google Chome, only LUTs with prefix `png/` are working as intended. 
Other LUT types like `neutral-` or `cube/` makes the scene turns completely black. 
I have to tick both `3D texture` and `tetrahedral filter` to make all LUT types work.
The document stated: `Tetrahedral interpolation produces highly accurate results, but is slower than hardware interpolation` so I'm hesitated to this config because I need to get the most out of performance.

(The default config working fine on Galaxy S20 exynos, the problem only occurs on S7)

**Comment by vanruesc** [comment]
Thanks for the report.

The S7 doesn't seem to support `FloatType` textures which the cube/3dl and neutral LUTs use by default. You can convert these textures into `UnsignedByteType` textures via `LookupTextured3D.convertToUint8()`.

I'll add checks for [OES_texture_float](https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float) and [OES_texture_float_linear](https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float_linear) to the demo to make it more robust.
