### ISSUE TITLE
Selectively excluding meshes from effectpass 

### ISSUE THREAD

**Issue by oddnugget** [vanruesc/postprocessing#303]
Hi, great library. I have spent a while now scouring through documentation in an attempt to exclude a certain mesh from being affected by an effect. This is due to the fact that we use shadowplanes for shadows, eg actual meshes with texture, and this messes up the look of many effects. 

Is this possible with this library? I have tried both implementations using `SavePass` and layers as well as  multiple render passses. The only option that i have left is to try to render two scenes and only apply the post processing to one of them, however I'd like to avoid that for performance reasons if possible. 

 Bellow is a sample of my attempt at following the advice seen in issues #295 and #229 
<img width="905" alt="Screenshot 2021-06-07 at 14 02 32" src="https://user-images.githubusercontent.com/72414261/121013690-74e4af80-c799-11eb-9b28-1b8b4a95cb19.png">

This however does not seem to work as the effect gets applied to the whole scene.

**Comment by oddnugget** [comment]
> A good way to determine if a certain composition is possible or not is to think of it in terms of photoshop layer blending. With postprocessing you can render anything to a texture. 

By that reasoning it does seem like it should be possible. I guess i'm falling short in the execution somewhere. 
>It would help a lot if you could provide a minimal example and a clear description of what kind of composition you're trying to create.

In short, all i want to do is exclude a mesh from being affected by the post process effect. Attemted here by putting it on a separate layer, and then trying to blend the texture of the effect onto the render without the effect.  This doesnt work, the post process is still affecting the shadowplane here. 

```js
          const effect = new NoiseEffect({
            blendMode: BlendFunction.SKIP,
            premultiply: true,
          });

          const fxSavePass = new SavePass();
          const textureFX = new TextureEffect({
            blendMode: BlendFunction.ADD,
            texture: fxSavePass.renderTarget.texture,
          });

          const blendPass = new EffectPass(camera, textureFX);

          effect.blendMode.opacity.value = 1;
          const shadowRender = new RenderPass(scene, camera);
          const effectRender = new RenderPass(scene, camera);
          const clearPass = effectRender.getClearPass();
          clearPass.color = false;
          clearPass.depth = false;
          effectRender.clear = false;

          composer.addPass(
            new LambdaPass(() => camera.layers.set(EFFECT_LAYER)),
          );
          composer.addPass(new EffectPass(camera, effect));
          composer.addPass(fxSavePass);

          // Shadow
          composer.addPass(
            new LambdaPass(() => camera.layers.set(SHADOW_PLANE_LAYER)),
          );
          composer.addPass(shadowRender);

          composer.addPass(new LambdaPass(() => camera.layers.set(0)));
    
```

Thanks for your swift reply!

**Comment by vanruesc** [comment]
This looks more like some kind of configuration issue to me. Try comparing your code with the following example: https://codesandbox.io/s/charming-violet-p6shu?file=/src/App.js

**Comment by oddnugget** [comment]
Do you have an example of excluding a layer from an effectpass?

**Comment by vanruesc** [comment]
Sorry for the delay, here's an example where noise is applied to one object: https://codesandbox.io/s/quirky-albattani-khdqq?file=/src/App.js

**Comment by oddnugget** [comment]
Thanks a lot! That is exactly what i was looking for.
