### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by clickstan** [vanruesc/postprocessing#306]
### Description of the bug

When trying to build the code (with "npm run build") , it produces the following error:

```
/Users/Stan/Downloads/postprocessing-main/esbuild.mjs:1
import { createRequire } from "module";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

### To Reproduce
Download the code, open the command line to the folder containing the download, first run `npm i `to install, then run `npm run build`

### Expected behavior

Should build the js from /src

### Screenshots

<img width="1112" alt="Screen Shot 2021-07-23 at 5 08 41 PM" src="https://user-images.githubusercontent.com/8376113/126841763-a45c0b8d-a270-418c-8c0c-979502ec31b8.png">

### Library versions used

The latest version downloaded (July 23)

### Desktop

 -Latest Mac OS (11.2.3)

**Comment by clickstan** [comment]
Any help would be appreciated- it seems like this is an error with the esbuild.mjs file- or am I missing something?

**Comment by vanruesc** [comment]
Hi, what version of node are you using? The `.mjs` extension enables node's ES module mode which is available since `node@13.2.0` without the `--experimental-modules` flag.

**Comment by clickstan** [comment]
Thanks, I was using version 10, updating to v16 seems to have fixed it. What a relief.
I came by to get a version of OutlinePass that works with animated meshes (not just morphTargets). Eg. like over here:
https://vanruesc.github.io/postprocessing/public/demo/#outline

Did that update get pushed into the official three.js yet? Do you know? Thanks again.

**Comment by vanruesc** [comment]
> Did that update get pushed into the official three.js yet?

No, and it is unlikely to happen due to API differences. Please not that this project is not compatible with three's post processing examples. You might also want to read [this wiki page](https://github.com/vanruesc/postprocessing/wiki/Skinned-and-Instanced-Meshes) regarding skinned meshes.
