### ISSUE TITLE
lazy loading  postprocessing in webpack 

### ISSUE THREAD

**Issue by isladjan** [vanruesc/postprocessing#307]
How to import asynchronously postprocessing in webpack Project and perform tree shaking. This doesn't work:

```
return Promise.all([
    ...
    import('postprocessing')
  ]).then(([
    ...
    { EffectComposer, RenderPass, EffectPass, BloomEffect, GodRaysEffect, SMAAEffect }
  ]))
```

**Comment by vanruesc** [comment]
Tree shaking only works on statically imported modules, and even then it can easily fail if a module contains problematic code. Dynamic imports  are ineligible for tree shaking.

**Comment by isladjan** [comment]
I found a solution: Create a new Module (ModulA) which will  load sync postprocessing. And then async load ModulA in main script:

ModulA:
```
import {EffectComposer, RenderPass, EffectPass, BloomEffect} from 'postprocessing';
export {
    EffectComposer,
    RenderPass,
    EffectPass,
    BloomEffect
}
```

Main script:
```
import('./ModulA.js').then(({EffectComposer, RenderPass, EffectPass, BloomEffect}) => {
       ...)
 });
```

**Comment by vanruesc** [comment]
Ah yeah, that works 👍
