### ISSUE TITLE
Lensflare disappears after passing options to EffectComposer

### ISSUE THREAD

**Issue by andregoncalvesdev** [vanruesc/postprocessing#308]
Hello!

I have a scene where i have two Lensflares. I want to activate AA for tier 3 benchmark machines, with the multisampling option on the EffectComposer, and as soon as i pass any option to the EffectComposer, the lensflares disappear. 

Quick example:
https://codesandbox.io/s/youthful-goldberg-8bqbf?file=/src/App.js

On the project i´m using three v0.124.0 and postprocessing v6.21.5.

Thank you.

**Comment by vanruesc** [comment]
Hi,

it looks like three's lens flare system is not compatible with multisampled frame buffers. I believe the same compatibility issue applies when a different frame buffer type is used.

Related: https://github.com/mrdoob/three.js/issues/16685

**Comment by andregoncalvesdev** [comment]
Thank you @vanruesc. It seems it is an 'won´t fix' issue,  so i have to find a workaround to the flares.

**Comment by vanruesc** [comment]
Yeah, we might need something like a `LensFlareEffect` in the long run. I'll tag this as a feature request and add a note to the roadmap.
