### ISSUE TITLE
How to change visible or hidden edge color after contructing OutlineEffect

### ISSUE THREAD

**Issue by Liron-Toledo** [vanruesc/postprocessing#310]
I simply cannot figure out how to change the hidden or visible edge colors of the outline effect after it has already been constructed. Can't seem to find docs anywhere showing me how to do this. Any way you can let me know how or if its even possible?

```
this.outlineEffect = new OutlineEffect(this.scene, this.selectedCamera, {edgeStrength: 2.0, visibleEdgeColor: '#FFFFFF', hiddenEdgeColor: '#FF0000', blur: true, blendFunction: THREE.NormalBlending});

// Want to be able to change the color later if certain requirements are met
this.outlineEffect.hiddenEdgeColor = '#FFFFFF'
```

**Comment by vanruesc** [comment]
Hi,

the `OutlineEffect` extends `Effect` which defines [uniforms](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/Effect.js~Effect.html#instance-member-uniforms) as a Map<String, [Uniform](https://threejs.org/docs/?q=uniform#api/en/core/Uniform)>. You can adjust the edge color like this:

```js
const uHiddenEdgeColor = outlineEffect.uniforms.get("hiddenEdgeColor");
uHiddenEdgeColor.value.setHex(0xffffff);

// Might need to convert to linear depending on where the color is coming from.
// uHiddenEdgeColor.value.convertSRGBToLinear();
```

Please note that the `OutlineEffect` expects hexadecimal values for the edge colors. Strings like `"#FFFFFF"` won't work.

**Comment by Liron-Toledo** [comment]
Hey, thanks so much this worked fo me. Really Appreciate it.
