### ISSUE TITLE
Creating separate OutlineEffects for different models.  

### ISSUE THREAD

**Issue by Liron-Toledo** [vanruesc/postprocessing#313]
Hey there, I have a question that I'm hoping you might be able help me with. I am attempting to create two different instances of an OutlineEffect. One that I want to use for 99% of my models and that only activates on mouse hover (lets call this effect1) and another that I use for a singular model that will be on at all times but have transparent visible edges so it can only be seen when occluded (effect 2). However, I'm seeing strange behaviour from trying to do this. For instance, effect1 is highlighting the singular object when any other model is highlighted and it seems all models are using the hiddenEdgeColor of effect2 in addition to the hiddenEdgeColor from effect1. It seems as if both effects are being applied to everything at the same time. Ill show you a snippet of my code below.

```

// Create effect composer
this.composer = new EffectComposer(this.renderer)
this.composer.addPass(new RenderPass(this.scene, this.camera))

// Add outline effect for single object (Only visible when occluded)  
this.singleOutlineEffect = new OutlineEffect(this.scene, this.selectedCamera, {edgeStrength: 2.0, visibleEdgeColor: '#000000', hiddenEdgeColor: Settings.currentSettings.color, blur: true, blendFunction: THREE.NormalBlending});
effects.push(this.avatarOutlineEffect)

// Add outline effect for rest of models and shapes           
this.outlineEffect = new OutlineEffect(this.scene, this.selectedCamera, {edgeStrength: 2.0, hiddenEdgeColor: '#FFFFFF', blur: false, blendFunction: THREE.NormalBlending});
effects.push(this.outlineEffect)
        
// Create effect pass
let pass = new EffectPass(this.selectedCamera, ...effects)
this.composer.addPass(pass)

```

Elsewhere in my code, I add effect2 to my singular object when the scene is loaded
```
this.singleOutlineEffect.selection.add(this.source.singleModel.outlineMesh[0])
```

I'm not entirely sure if what I'm trying to do is even possible or if perhaps there is a way to select a singular rendering target that I'm not aware of either way I've been kinda stuck for the last few hours trying to figure this out so thought asking here couldn't hurt. Thanks in advance for any help you can give me!

**Comment by vanruesc** [comment]
Your effects are using the same [render layer](https://threejs.org/docs/?q=layer#api/en/core/Layers). The `OutlineEffect` uses a [Selection](https://vanruesc.github.io/postprocessing/public/docs/class/src/core/Selection.js~Selection.html) to keep track of selected objects. If you want to use multiple outline effects, you'll need to make sure the selections use different [layers](https://vanruesc.github.io/postprocessing/public/docs/class/src/core/Selection.js~Selection.html#instance-get-layer):

```js
const outlineEffect1 = new OutlineEffect(...);
const outlineEffect2 = new OutlineEffect(...);

outlineEffect1.selection.layer = 10; // Default layer, usable range is [1, 31].
outlineEffect2.selection.layer = 11;
```

**Comment by Liron-Toledo** [comment]
@vanruesc omg is what that simple all along. This is exactly what i needed. Fixed all the issues I was seeing. Can't thank you enough!
