### ISSUE TITLE
Background Always White. 8thWall Project

### ISSUE THREAD

**Issue by UMUTBAYGUT** [vanruesc/postprocessing#317]
I read the old issue about same with my problem. 

But I can not fix still. 

Created a new small project about it.Still I can not found why background is always white. 
Branch : posteffective_library
https://github.com/UMUTBAYGUT/BloomTest

**Comment by vanruesc** [comment]
Your WebGL context parameters (`antialias`, `alpha`, `depth`, ...) [will be ignored](https://github.com/mrdoob/three.js/blob/f1048891d978beb69b81a34c604641cf4caa2f47/src/renderers/WebGLRenderer.js#L223) if you [provide a custom context](https://github.com/UMUTBAYGUT/BloomTest/blob/f8c7cb29e5dda4d07b79ddf352c0187638e26eab/js/helper.js#L4). Therefore, your context is probably not using alpha. I don't know where `GLctx` is coming from, but you'd need to create that context with `alpha` set to `true`.

Also note that you need to set event listeners for `webglcontextlost` and `webglcontextrestored` on the custom canvas if not done already. See https://www.khronos.org/webgl/public-mailing-list/public_webgl/1703/msg00022.php for details.

**Comment by UMUTBAYGUT** [comment]
Hi  @vanruesc ;
I am not using helper file now. I take the rendere object from 8thWall (https://github.com/UMUTBAYGUT/BloomTest/blob/f8c7cb29e5dda4d07b79ddf352c0187638e26eab/js/testpipeline.js#L22)  (https://github.com/UMUTBAYGUT/BloomTest/blob/f8c7cb29e5dda4d07b79ddf352c0187638e26eab/js/modelsjs/profilePhoto.js#L41) 

I can not any information to change alpha value for 8thwall renderer object.

**Comment by vanruesc** [comment]
I've only skimmed through [the documentation](https://www.8thwall.com/docs/web/#xr8run) but it seems to be possible to set context parameters as follows:

```js
XR8.run({canvas: document.getElementById('camerafeed'), glContextConfig: {alpha: false, ...}})
```

This repository isn't really the right place to ask questions about external project like 8thWall though. You'd probably have better chances of getting reliable answers by using their channels: https://www.8thwall.com/resources & https://github.com/8thwall/web.

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
