### ISSUE TITLE
Passing a render target texture to a custom effect

### ISSUE THREAD

**Issue by thibka** [vanruesc/postprocessing#323]
Hi,

Here's what I'm trying to do, but I'm not 100% sure I'm using the right approach: 
1. Render the scene
2. Apply some classic postprocessing passes
3. Then save the current state of the render as a texture
4. Add a final custom effect pass. This would be a shader that receives the texture as a uniform before outputting the final result.

Here's what I've tried:
```javascript
const savePass = new SavePass();
const texturePass = new EffectPass(camera, new TextureEffect({
    texture: savePass.renderTarget.texture
}));

const customEffect = new Effect('custom', /* glsl */`
    uniform sampler2D uTexture;

    void mainImage(const in vec4 inputColor, const in vec2 uv, out vec4 outputColor) {
        vec4 textureColor = texture2D(uTexture, uv);

        //outputColor = vec4(inputColor.r, 0.0, 0.0, 1.0); // works as expected
        outputColor = vec4(textureColor.rgb, 1.0); // doesn't work
    }
`, {
    blendFunction: BlendFunction.NORMAL,
    uniforms: new Map([
        ['uTexture', savePass.renderTarget.texture]
    ])
});
const customPass = new EffectPass( camera, customEffect );

composer.addPass(renderPass); // renders the scene
composer.addPass(effectPass); // adds some classic postprocessing
composer.addPass(savePass); // saves the current state as a texture?
composer.addPass(customPass); // adds one last custom pass using this texture?
```

Here's a sandbox: 
https://codesandbox.io/s/green-tdd-gcf11?file=/src/App.js

The outcome is just a black screen, so does this approach even make sense? 
Any help would be greatly appreciated!

**Comment by vanruesc** [comment]
The values in the `uniforms` map are expected to be `Uniform` instances:

```js
    ...
    uniforms: new Map([
        ['uTexture', new Uniform(savePass.renderTarget.texture)]
    ])
});
```

https://codesandbox.io/s/sleepy-vaughan-o30dh

**Comment by thibka** [comment]
Ooh, so that's what is was!
Thank you so much for your support, once again you're a life saver ❤️
