### ISSUE TITLE
Support for three.js r135

### ISSUE THREAD

**Issue by discosultan** [vanruesc/postprocessing#327]
https://github.com/vanruesc/postprocessing/blob/a3c97453ba9e7fcd3f5435248409acb73b09e6a2/package.json#L76

**Comment by vanruesc** [comment]
Thanks for the report!

The peer dependency specifies versions of `three` thare are currently guaranteed to work with `postprocessing`. It's mostly a recommendation and `postprocessing` usually works with the latest revision of `three`. However, there have been breaking changes in `three` r133 and now in r135 related to `SRGB8_ALPHA8` that require back-compat adjustments in `postprocessing`.

It's on my radar and I'm going to push a new release tomorrow that addresses this.

**Comment by marcofugaro** [comment]
Just an heads up, [`SRGB8_ALPHA8` will be enabled again in r136](https://github.com/mrdoob/three.js/pull/22952)
