### ISSUE TITLE
SSAO invisible when multisampling enabled

### ISSUE THREAD

**Issue by discosultan** [vanruesc/postprocessing#329]
### Description of the bug

SSAO effect becomes invisible when multisampling is enabled.

Maybe it's intented in which case this ticket is more of a question of why. In this case, perhaps it makes sense to add a note to the `SSAOEffect` comments.

### To Reproduce

See https://codesandbox.io/s/priceless-rgb-g1izu?file=/src/App.js:1468-1469. Change the multisampling value on `EffectComposer` to reproduce.

### Library versions used

 - Three: 0.135.0
 - Post Processing: 6.23.3

----

Possibly related to https://github.com/vanruesc/postprocessing/issues/100

**Comment by vanruesc** [comment]
Hi, thanks for the report!

The provided sandbox works with multisampling enabled when you downgrade `three` to r134. This appears to be a known regression: https://github.com/mrdoob/three.js/issues/22967.

**Comment by discosultan** [comment]
Fixed with the release of three.js 0.136.0.
