### ISSUE TITLE
How to update the uniforms of an Effect

### ISSUE THREAD

**Issue by thibka** [vanruesc/postprocessing#335]
Hi,

I know how to update the uniforms of a custom Effect, but I'm not sure how to that with the included ones.
For instance, with a ChromaticAberrationEffect like this:
```javascript
composer.addPass( new EffectPass( camera,
    new ChromaticAberrationEffect({
        offset: new THREE.Vector2(.005, 0)
    }),
));
```
How could I update the offset?

Thanks!

**Comment by vanruesc** [comment]
The offset uniform can be accessed via the [uniforms](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/Effect.js~Effect.html#instance-member-uniforms) field: `effect.uniforms.get("offset").value.x = 0;`. This effect also provides an `offset` getter which acts as a shortcut: `effect.offset.value.x = -0.004;`.

**Comment by thibka** [comment]
Excellent, thanks @vanruesc 🙏

**Comment by vanruesc** [comment]
FYI: the `offset` getter has been superseded by `getOffset()` and `setOffset()` in `postprocessing@6.24.0`.
