### ISSUE TITLE
setRenderer method for EffectComposer

### ISSUE THREAD

**Issue by alexpineda** [vanruesc/postprocessing#337]
### Is your feature request related to a problem?

I'd like to keep a single reference to effect composer (for mutability reasons) and assign a renderer at a later date. Presently when I do so I have to also include a copy of the code that is in the EffectComposer constructor.

```js
  this.composer.renderer = renderer;
  this.composer.renderer.autoClear = false;

  // my settings
  this.composer.inputBuffer = this.composer.createBuffer(
      true,
      false,
      HalfFloatType,
      4
  );

  this.composer.outputBuffer = this.composer.inputBuffer.clone();
```

### Describe the solution you'd like

Use a `setRenderer` method to assign these properties instead of having it done in the constructor.

```js
// in the constructor
if (renderer) {
  this.setRenderer(renderer, { depthBuffer, stencilBuffer, multisampling, frameBufferType });
}

// the new method
/**
* Sets the WebGLRenderer
*
* @param {WebGLRenderer} renderer - The renderer that should be used.
* @param {Boolean} [options.depthBuffer=true] - Whether the main render targets should have a depth buffer.
* @param {Boolean} [options.stencilBuffer=false] - Whether the main render targets should have a stencil buffer.
* @param {Number} [options.multisampling=0] - The number of samples used for multisample antialiasing. Requires WebGL 2.
* @param {Number} [options.frameBufferType] - The type of the internal frame buffers. It's recommended to use HalfFloatType if possible.
*/
setRenderer(renderer, {
		depthBuffer = true,
		stencilBuffer = false,
		multisampling = 0,
		frameBufferType
	} = {}) {

    this.renderer = renderer;
    this.renderer.autoClear = false;
  
    this.inputBuffer = this.createBuffer(
      depthBuffer,
      stencilBuffer,
      frameBufferType,
      multisampling
    );
  
     this.outputBuffer = this.inputBuffer.clone();

}
```

### Describe alternatives you've considered

Have `replaceRenderer()` initialize input and output buffers if `oldRenderer == null`.

**Comment by vanruesc** [comment]
Thanks for reporting this. It's an oversight that `replaceRenderer` doesn't properly prepare the buffers. I'll take a closer look at this in a bit.

I think it's a good idea to add a `setRenderer` method to replace `replaceRenderer`. The new method should probably also inform all passes about the new renderer. I'm not sure about the extra options though. Do you change these settings when you set a different renderer? I think it would be more appropriate to create a new composer in those cases.

I'm currently working on moving the frame buffer management out of the composer, so it won't need those options anymore. But that will land later in v7 with other breaking changes.

**Comment by alexpineda** [comment]
You're welcome. To your point, I don't change settings when creating a new renderer. For simplicity sake I did not add any class members in the example, which could have recalled these values again in setRenderer without needing all those arguments again.

**Comment by vanruesc** [comment]
Added `setRenderer` method in `postprocessing@6.24.0`.
