### ISSUE TITLE
RGBFormat is not supported anymore by Threejs

### ISSUE THREAD

**Issue by Makio64** [vanruesc/postprocessing#338]
### Description of the bug

The last version of threejs remove RGBFormat Support ( to align with webgpu )

More infos:
https://github.com/mrdoob/three.js/pull/23228
https://github.com/mrdoob/three.js/releases/tag/r137

### To Reproduce

Start postprocessing + latest threejs ( r137 )

### Expected behavior

Work with latest threejs

### Library versions used

 - Three: [ 0.137.0]
 - Post Processing: [ latest ]

**Comment by Makio64** [comment]
I tried to do a fast patch replacing ``import RGBFormat as ..`` by ``import RGBAFormat as ..`` and it almost works excepted a problem with clearing buffer

r137 without Postprocessing
![image](https://user-images.githubusercontent.com/213351/151348955-131efaad-f1d8-4f35-ac08-cd2dedab7757.png)

r137 with Postprocessing fast patch & only RenderPass
![image](https://user-images.githubusercontent.com/213351/151349141-5276ff5e-99f7-4ee8-bb1b-b7f111317ad2.png)

**Comment by vanruesc** [comment]
Thanks for the report. I'm already working on a backward-compatible solution. Please note that `postprocessing@6.23.5` does not officially support three r137 precisely because `three` tends to introduce breaking changes every once in a while.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.24.0`.
