### ISSUE TITLE
OutlineEffect and Instanced Mesh

### ISSUE THREAD

**Issue by k2xl** [vanruesc/postprocessing#339]
Does Outline Effect support instanced meshes?
When doing ...
`outlineEffect.selection.add(mesh)`
when mesh is a regular mesh it seems to work, but when I try adding an instancedMesh it gives this error:

`app.js:26287 Uncaught TypeError: Cannot read properties of undefined (reading 'layers')`

Will outlineeffect work with instanced meshes?

**Comment by vanruesc** [comment]
Hm, it should work. Are you sure you're not passing `undefined` to `selection.add()`?

**Comment by k2xl** [comment]
@vanruesc *smacks forehead* Yup - wow. This will teach me to console.log better in the future :-P.
