### ISSUE TITLE
Latest version has a potential of breaking if used with the dev version of threejs

### ISSUE THREAD

**Issue by RenaudRohlinger** [vanruesc/postprocessing#345]
https://github.com/vanruesc/postprocessing/blob/fbc246e2959e9e543f6641c6af76ec4adfe8db58/src/materials/glsl/effect/shader.frag#L38

Hello! For your information, this will break if a developer works with the dev version of threejs and postprocessing as the revision number is usually 13Xdev and not just an integer.

Maybe simply substring dev from the revision would be enough?

**Comment by vanruesc** [comment]
Thanks for pointing that out!

> Maybe simply substring dev from the revision would be enough?

Yes, something like `REVISION.replace( /\D+/g, "")` in [EffectMaterial](https://github.com/vanruesc/postprocessing/blob/fbc246e2959e9e543f6641c6af76ec4adfe8db58/src/materials/EffectMaterial.js#L44) should do it. Would you like to make a PR?

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.24.1`.
