### ISSUE TITLE
would pp accept a single types file?

### ISSUE THREAD

**Issue by drcmda** [vanruesc/postprocessing#350]
we maintain https://github.com/pmndrs/react-postprocessing/blob/master/types/postprocessing.d.ts but it currently only benefits react devs.

is pp interesting in shipping that + package.json:types: "types/postprocessing.d.ts"

even without using types at all they aid IDE autocompletion and info-on-hover. it pretty much spares us from visiting docs and a single cmd-click on something goes to all possible props, for instance if i can't remember the props that "bloom" takes i just click it. for those that do use TS (i don't personally), i guess it also safeguards the code.

another option could be @types/postprocessing

**Comment by vanruesc** [comment]
> is pp interesting in shipping that + package.json:types: "types/postprocessing.d.ts"

Yes, this should be fine as a temporary solution considering that the full TypeScript conversion is probably still a couple of months away.

**Comment by vanruesc** [comment]
Right, if you're okay with waiting a little longer, there's no need for action. But if you or someone else wishes to add a `d.ts` file, feel free to send a PR.
