### ISSUE TITLE
Sobel messes up Environment in 6.24.1

### ISSUE THREAD

**Issue by LorenzWieseke** [vanruesc/postprocessing#353]
### Description of the bug

When I update from 6.23.3 to 6.24.1 somehow after activating the Sobel effect my environment reflection is messed up.
[](URL)

Changing the Environment will work but when I change it back it's still not working right.

### To Reproduce
With 6.23.3
https://platform.govie.de/share/draft/F9ALTRzy3uRsfpNAo?Datsun-GT

With 6.24.1
https://beta.govie.de/share/draft/F9ALTRzy3uRsfpNAo?Datsun-GT

### Screenshots

![24 1_before_Sobel](https://user-images.githubusercontent.com/29607121/156349976-95fd607a-99ae-433b-9858-c6452edb7c30.jpg)
![24 1_Sobel](https://user-images.githubusercontent.com/29607121/156349977-c95ecb23-5b3e-489d-8bb2-942676dfb072.jpg)
![24 1_after_Sobel](https://user-images.githubusercontent.com/29607121/156349973-c918c0ee-f1d3-4bb1-a927-85efb56cb371.jpg)

### Library versions used

 - Three: 0.135 / tested also on 137 and 138.2
 - Post Processing: 6.24.1

### Desktop

 - OS: Windows 10 / 11
 - Browser Chrome 98.0.4758.102 
 - Graphics hardware:  NVIDIA GTX 3070

### Mobile

 - OS: [e.g. Android 10]
 - Browser [e.g. Firefox 68.11.0]

**Comment by vanruesc** [comment]
Does the effect work when you're using `postprocessing@6.23.3` in combination with `three` r135, r136, r137 and r138? If not, does it break when you use  `postprocessing@6.23.4`? Or does it only break when you use  `postprocessing@6.24.x`? It's important to identify the exact point where it breaks to figure out what could cause it and if it's exclusively related to `three`. 

The error could be in the Environment setup of this particular app or in the mentioned Sobel effect which is _not_ included in `postprocessing`. It would be easier to debug this if you could provide a minimal reproduction of the issue.

**Comment by LorenzWieseke** [comment]
So we spend some time and figured out:
1. its not about the sobel, it happens with any of the effects
2. it was the pass.dispose() that somehow cleared something
3. tried to set pass.renderer = null before so its not getting cleared but that didn't help, exclude clearPass or renderTarget from dispose didn't work cause we use  _composer.removeAllPasses()
4. no we just stick with removing pass.dispose hoping the GPU memory doesn't get to full, but using the chrome task manger shows me the size is staying the same

**Comment by vanruesc** [comment]
Thanks for investigating!

This looks like an unintended side-effect of the `Pass.dispose` and `Effect.dispose` methods that went unnoticed during the recent changes. Since `postprocessing@6.24.0`, passes and effects keep a reference to the renderer and since it has a `dispose` method, it will automatically be disposed whenever a pass or effect is disposed.

I'll release a fix in a bit.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.25.0`. Sorry for the delay!
