### ISSUE TITLE
Blurry results on retina display.

### ISSUE THREAD

**Issue by izar89** [vanruesc/postprocessing#48]
The renderer pixelRatio property gets ignored when setting the size of the THREE.WebGLRenderTarget. This results in a write and read buffer that's 1/4 the size (pixelRatio = 2) of the canvas which means the rendered result gets upscaled and will look blurry on screens with a higher pixelRatio. You can fix  this by multiplying the width and height with the pixelRatio when setting the size of the THREE.WebGLRenderTarget.
```
const pixelRatio = this.renderer.getPixelRatio();
new THREE.WebGLRenderTarget(size.width * pixelRatio, size.height * pixelRatio, ...
```
![postprocessing_retina](https://cloud.githubusercontent.com/assets/767371/21158637/43bfef80-c17e-11e6-86fd-7f8b36f38108.png)

I can send a pr when I find some time.
:)

**Comment by vanruesc** [comment]
Hi,

thanks for the issue report!

I'm currently fully invested in another project, but I'm planning on revising a lot of the code in this repository when I finally have more time.

Feel free to send a PR, I'll take a look at it if time permits 😅

**Comment by vanruesc** [comment]
Just a heads up, this issue might be fixed by now! I didn't get to test it, though.

**Comment by vanruesc** [comment]
Closing this since the problem seems to be solved.
