### ISSUE TITLE
BloomFilter broken on Edge > 38

### ISSUE THREAD

**Issue by TomSlezakowski** [vanruesc/postprocessing#55]
After some initial digging, it seems that the 'range' value of the LuminosityMaterial needs to be defined as a 2d Vector rather than null, if no range is specified. 

I haven't had time to build out an example case but if this is something you want to address, I'll happily expand on this tomorrow when I have a dab more time!

**Comment by vanruesc** [comment]
Sounds interesting!

I don't use Edge, so I'll rely on your findings. Also, reverting 4428c91 might just do the trick.

**Comment by TomSlezakowski** [comment]
Ahh! That's basically the exact change I made in my brief test. 

Our project had to support Edge and pressed for time, we just ended up disabling Bloom. It would be neat to get to the bottom of though, it seems like all other postprocessing filters work great in Edge!

**Comment by vanruesc** [comment]
I reverted said commit since it's better to avoid ```null``` uniforms altogether, The fix is included in v2.1.1.
The ```BloomPass``` should now work in Edge, so I'm closing this for now. If it's still broken, let me know!
