### ISSUE TITLE
FilmPass && SMAAPass == blackscreen

### ISSUE THREAD

**Issue by stephanedemotte** [vanruesc/postprocessing#59]
Hi, 

I try to use postprocessing with aframe.

I can use FilmPass and SMAAPass individualy, but when i try to use both, boom black screen.

```
import { EffectComposer, FilmPass, RenderPass, SMAAPass } from "postprocessing"

const composer = new THREE.EffectComposer(renderer)
// have to use THREE.EffectComposer instead of EffectComposer because of aframe.
const renderPass = new RenderPass(scene, camera)

const filmPass = new FilmPass({
      grayscale: false,
	sepia: false,
	vignette: true,
	eskil: false,
	scanlines: false,
	noise: true,
	noiseIntensity: 0.5,
	scanlineIntensity: 0.5,
	scanlineDensity: 1.5,
	greyscaleIntensity: 1.0,
	sepiaIntensity: 1.0,
	vignetteOffset: 0.5,
	vignetteDarkness: 0.5
    })

    const smaaPass = new SMAAPass(Image)

    smaaPass.renderToScreen = true

    composer.addPass(renderPass)
    composer.addPass(filmPass)
    composer.addPass(smaaPass)

```
Maybe you can help ?

Thanks you !

**Comment by vanruesc** [comment]
Hi,

your setup looks good to me. I tried using the FilmPass together with the SMAAPass and it worked just fine, but I didn't use aframe.

> have to use THREE.EffectComposer instead of EffectComposer because of aframe.

Could you elaborate on this? If you're not using the `EffectComposer` from the postprocessing library, the passes may not be initialised properly.

It would be great if you could provide more information or even a simple JSFiddle to reproduce the blackscreen. In the meantime, I'll take a closer look at aframe.

**Comment by stephanedemotte** [comment]
Hi, thanks for your feedback.

It work know, here all you need to make it run with aframe.
I have to declare 2 times EffectComposer and boom work.

```
import { EffectComposer, FilmPass, RenderPass, SMAAPass } from "postprocessing"

AFRAME.registerSystem('postprocessing', {
  init() {
    const sceneEl = this.sceneEl

    if(!sceneEl.hasLoaded)
      return sceneEl.addEventListener('render-target-loaded', this.init.bind(this))

    const scene = sceneEl.object3D
    const renderer = sceneEl.renderer
    const render = renderer.render
    const camera = sceneEl.camera

    // the magic trick
    // why ? don't know, but work ;)
    // maybe because we have 2 WebGlTarget in VR
    new EffectComposer(renderer)

    // one more effect composer
    const composer = new EffectComposer(renderer)
    const renderPass = new RenderPass(scene, camera)

    const filmPass = new FilmPass({
      grayscale: false,
      sepia: false,
      vignette: true,
      eskil: false,
      scanlines: false,
      noise: true,
      noiseIntensity: 0.5,
      scanlineIntensity: 0.5,
      scanlineDensity: 1.5,
      greyscaleIntensity: 1.0,
      sepiaIntensity: 1.0,
      vignetteOffset: 0.5,
      vignetteDarkness: 0.5
    })

    const smaaPass = new SMAAPass(Image)
    smaaPass.renderToScreen = true

    composer.addPass(renderPass)
    composer.addPass(filmPass)
    composer.addPass(smaaPass)

    const clock = new THREE.Clock()
    let isDigest = false

    renderer.render = function() {
      if(isDigest)
        return render.apply(this, arguments)

      isDigest = true
      composer.render(clock.getDelta())
      isDigest = false
    }
  }
})
```

**Comment by vanruesc** [comment]
That's a really weird fix, but I'm glad that it works for you now 😅 

Creating a second `EffectComposer` shouldn't actually do anything, though. I played around with aframe in this [example setup](https://jsfiddle.net/p56agpjh/1/) and as you can see, I'm only using one composer here. Maybe something else caused the blackscreen in your case.

Btw: I recommend adding the `SMAAPass` before the `FilmPass`. This way, the noise won't confuse the SMAA edge detection.

**Comment by stephanedemotte** [comment]
Haha !

Thanks a lot for your code, tips and your post process lib !! Great job !
