### ISSUE TITLE
Bloom Pass: Shader couldn't compile for 'linearToRelativeLuminance'.

### ISSUE THREAD

**Issue by AlexanderPaule** [vanruesc/postprocessing#63]
Hi, thanks you for this library, it's amazing.

It's the first time that i find a problem that I'm not able to solve related to your library.

**OS: Windows 7 x64**
**Chrome Version: 61.0.3163.100**

My problem is the following.

I have this error in console only when **BloomPass** is active.

```
THREE.WebGLShader: Shader couldn't compile
THREE.WebGLShader: gl.getShaderInfoLog() fragment ERROR: 0:171: 'linearToRelativeLuminance' : no matching overloaded function found
THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog invalid shaders
ERROR: 0:171: 'linearToRelativeLuminance' : no matching overloaded function found
WebGL: INVALID_OPERATION: useProgram: program not valid
```

[Complete Error Stack Trace](https://github.com/vanruesc/postprocessing/files/1433854/ErrorStackTrace.txt)

I'm working on Angular4 and Typescript and  I've tested the application in Angular2 Too, but the error stack trace is the same.
I've tested it only on Chrome, and I don't know if error appears on other browsers.

I've also tried to take a look at the shader program, but my knowledge in OpenGL are very limited and I've not been able to find a solution.

Can you help me to understand what went wrong?

**Comment by vanruesc** [comment]
Hi Alexander,

thanks for reporting this issue!

For some reason I thought that the `linearToRelativeLuminance` function was introduced in `three.js@0.87.x` but that's not the case. The postprocessing demo works because it currently uses the dev version `three.js@0.88.x` in which the function is available.

Will fix this ASAP.

**Comment by AlexanderPaule** [comment]
Thank you @vanruesc 
Now all works fine!

Thanks a lot
