### ISSUE TITLE
Not enough installation instructions

### ISSUE THREAD

**Issue by alfredoBorboa** [vanruesc/postprocessing#66]
Hi! Great library!
I'm just struggling to get everything running:
a) Just using bare ES6 imports, and
b) Using Typescript + webpack.

I've failed miserably both times. Where can I check more detailed info on how to get this up and running? The provided example is not enough as it has already been webpacked.

**Comment by alfredoBorboa** [comment]
Nevermind :) Sorry; late night coding is not the best.

**Comment by vanruesc** [comment]
Hi!

I was about to provide a working example setup, but I guess that's no longer necessary. I'm glad that you were able to resolve your problem 👍
