### ISSUE TITLE
Module should point to ES build

### ISSUE THREAD

**Issue by sasha240100** [vanruesc/postprocessing#69]
Hello @vanruesc ,
Thanks for your amazing work with this postprocessing library for Three.js!

However, I have some problems with making UglifyJS while building module that includes your library. And this happens because of this line(7):
![image](https://user-images.githubusercontent.com/7657429/36639613-0e23512e-1a19-11e8-96ee-2d9e367df1be.png)

Could you please make it something like: `"module": "build/postprocessing.module.js"` which is a completely ES5 (thanks, Babel) except that it has ES6 harmony module syntax in exporting (or importing external libraries)

For example, in RollupJS such option is possible if you specify `format: 'es'`. https://rollupjs.org/guide/en#exporting

**Comment by vanruesc** [comment]
Hi,

I'd argue that the issue you're facing is not an issue with the `postprocessing` library, but with UglifyJS which doesn't support ES2015+ syntax. There's [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony) now which might get the job done, though.

I don't know your build setup, but the most common way to resolve this incompatibility issue is to use `babel` on your end to transpile your final bundle and then use UglifyJS for minification as a final step.

A transpiled bundle is provided under `package.main` for backward compatibility only. In my opinion, `package.module` should always point to the _untranspiled_ source code (or bundle using `format: es`). This way, it's up to the consumer how the source code is used or transformed. Providing transpiled code under `package.module` effectively counteracts the creation of modern ES2015+ bundles which might become the norm in the future.

I hope you understand my point of view on this matter 😅

**Comment by vanruesc** [comment]
Alright, I'm closing this then 😊 

Thanks for starting the discussion! Changes that seem simple at first sometimes hide serious implications. It's always good to talk about stuff like that.
