### ISSUE TITLE
OutlinePass setSelection performs clear operation in incorrect order

### ISSUE THREAD

**Issue by stevesch** [vanruesc/postprocessing#75]
I believe for the intent of OutlinePass.setSelection,

this.clearSelection() in OutlinePass.js should be performed before the "for" loop that sets the newly selected items' layer.
(current line 373, move to line 364, just after the two "const" declarations)

**Comment by vanruesc** [comment]
Hi,

thanks for taking the time to point this out!

You're right, the current implementation incorrectly assumes that the given list of objects doesn't contain objects that are already selected. As a result, the selection layer will unintentionally be disabled for objects that are in both lists.

I'll fix this ASAP.

**Comment by vanruesc** [comment]
Fixed in `postprocessing@4.4.1`.
