### ISSUE TITLE
Demo source code

### ISSUE THREAD

**Issue by spinjam** [vanruesc/postprocessing#84]
Could you publish the source code of the demo (https://vanruesc.github.io/postprocessing/public/demo)?
I'm trying to replicate the film effect but this is the result with default options:
![the-watcher-capture-03](https://user-images.githubusercontent.com/1153842/41277453-980f9e62-6e27-11e8-8e03-57a58bfe72f4.PNG)

**Comment by vanruesc** [comment]
Hi,

the source code is published [here](https://github.com/vanruesc/postprocessing/tree/master/demo/src). The `FilmPass` configuration can be found [here](https://github.com/vanruesc/postprocessing/blob/master/demo/src/demos/FilmDemo.js#L180-L197).

In the past, I moved some of the demo code into an external module called [three-demo](https://github.com/vanruesc/three-demo) to reduce code duplication in my other projects. The demo also depends on the [delta-controls](https://github.com/vanruesc/delta-controls) module for the camera movement.

**Comment by spinjam** [comment]
Thank you, I forgot to specify width and height of the renderer
`this.renderer.setSize(window.innerWidth,window.innerHeight);`
and all the rendering passes take a very low resolution.

**Comment by vanruesc** [comment]
Please note that the render size should be set via `EffectComposer.setSize(width, height)`. This way the passes will be updated as well.

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
