### ISSUE TITLE
Why 'type' param is passed as material parameter?

### ISSUE THREAD

**Issue by KrzysztofBogdan** [vanruesc/postprocessing#87]
I am not sure why you pass type parameter in material params, for example:
https://github.com/vanruesc/postprocessing/blob/edd93e7f62472cddee25d9ee4f733b5098a0f8b9/src/materials/ColorEdgesMaterial.js#L24

I do not any usage of such a field in three.js code. 

Maybe it should be set manually (https://threejs.org/docs/#api/materials/Material.type) like:
https://github.com/mrdoob/three.js/blob/a8286453eade9bc3b1f14451ea3d337e805d1906/src/materials/MeshLambertMaterial.js#L47 ?

**Comment by vanruesc** [comment]
Hi,

the materials in this library extend `ShaderMaterial` which sets parameters via `Material.setValues(parameters)`:

https://github.com/mrdoob/three.js/blob/dev/src/materials/ShaderMaterial.js#L68-L78
https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L80-L134

**Comment by KrzysztofBogdan** [comment]
Ohh, I missed that, sorry to bother!

**Comment by vanruesc** [comment]
No problem 👍
