### ISSUE TITLE
OutlinePass - bad output buffer

### ISSUE THREAD

**Issue by KrzysztofBogdan** [vanruesc/postprocessing#88]
I am not 100% sure but it seems that:
https://github.com/vanruesc/postprocessing/blob/edd93e7f62472cddee25d9ee4f733b5098a0f8b9/src/passes/OutlinePass.js#L607

there should be just "outputBuffer" instead of "this.outputBuffer"

**Comment by vanruesc** [comment]
Fixed in `postprocessing@4.8.2`.
