### ISSUE TITLE
Antialiasing disabled when using Godrays

### ISSUE THREAD

**Issue by Thibka** [vanruesc/postprocessing#89]
I'm using the Godrays pass, which works well. 
But then, the antialiasing seems to be disabled. Is it possible to have both antialiasing and a godrays pass?

I'm thinking one solution could be to use a SMAA pass, but I've no idea how it supposed to work. 
After some digging, I've realized that the demo page 
https://github.com/vanruesc/postprocessing/blob/master/demo/src/demos/SMAADemo.js
and the actual class
https://github.com/vanruesc/postprocessing/blob/master/src/passes/SMAAPass.js
were quiet different, which adds to my confusion :)

**Comment by vanruesc** [comment]
Hi,

antialiasing doesn't work on offscreen render targets in WebGL 1. All post processing effects suffer from this. WebGL 2 supports multisampled render buffers but `three.js` doesn't fully support that context yet.

> Is it possible to have both antialiasing and a godrays pass?

Yes, the `SMAAPass` implements efficient antialiasing for post processing pipelines.

> I've no idea how it supposed to work.

The [SMAAPass](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/SMAAPass.js~SMAAPass.html) constructor requires two special data images that have to be loaded asynchronously. The actual image data is exposed to the user as [SMAAPass.searchImageDataURL](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/SMAAPass.js~SMAAPass.html#static-get-searchImageDataURL) and [SMAAPass.areaImageDataURL](https://vanruesc.github.io/postprocessing/public/docs/class/src/passes/SMAAPass.js~SMAAPass.html#static-get-areaImageDataURL). Here's a condensed example of how to load them: [SMAA Example](https://jsfiddle.net/tcs06j47/).

Note that the default antialiasing should be disabled when using post processing effects.

**Comment by Thibka** [comment]
Works like a charm :) 
Thank you so much!
