### ISSUE TITLE
Absolutely incredible work on v5 - examples of chaining shaders, new comparative performance benchmarks?

### ISSUE THREAD

**Issue by gigablox** [vanruesc/postprocessing#96]
I was reviewing your changes for the past couple hours, seeing where all that work went into for the v5 PR and https://github.com/vanruesc/postprocessing/issues/82 milestone. It's incredible how much time and thought you put into this.

Correct me if I'm wrong but this combines passes much more efficiently than the ThreeJS `EffectPass` class  because you are combining shaders and running a single pass rather then multiple passes over each?

I'd love to see some examples of chaining shaders together, I can even submit a PR for that to add to your examples for FPS experimentation.

**Comment by vanruesc** [comment]
Thank you!

> this combines passes much more efficiently than the ThreeJS EffectPass class because you are combining shaders and running a single pass rather then multiple passes over each?

Yes, well, the ThreeJS examples don't contain an `EffectPass`. That's a new addition in this library. But apart from that you're spot on.

The fundamental concept of passes is still there, too, and it actually hasn't changed at all. Effects, however, offer the possibility to programmatically opt into shader merging via the `EffectPass`. In my opinion, it's important that the user knows what's happening and why it's happening. The concept of effects supports that quite nicely. Another feasible option would have been to sneakily analyze and merge all kinds of passes behind the back of the user. But I discarded that idea early on.

> I'd love to see some examples of chaining shaders together

Do you mean really long effect chains? All the demos already use effect chaining. For example, the [color correction demo](https://vanruesc.github.io/postprocessing/public/demo/#color-correction) chains the `SMAAEffect`, `BrightnessContrastEffect`, `GammaCorrectionEffect` and `HueSaturationEffect`. You could also plug in a `BloomEffect`, `GodRaysEffect`, `VignetteEffect`, and lots of other effects and you'd still have a single fullscreen render operation. Well, to be fair, the `BloomEffect` and `GodRaysEffect` render some additional textures off-screen, but that can't be avoided.

The only effects that cannot be merged _with each other_ are `BokehEffect`, `RealisticBokehEffect`, `ChromaticAberrationEffect`, `GlitchEffect`, `PixelationEffect`, `ShockWaveEffect` and `SMAAEffect`. To use those effects together, you'd have to use multiple `EffectPass` instances. But the user doesn't have to worry about that too much; if something doesn't work, the `EffectPass` will complain.

> I can even submit a PR for that to add to your examples for FPS experimentation.

That would be nice. If you need assistence, I'm here!

**Comment by vanruesc** [comment]
I've added a performance demo that uses 14 mergeable effects.

#### Test system:
CPU: AMD Ryzen 1600x
GPU: NVIDIA GTX 1060 6Gb
RAM: G.Skill 16Gb 3200Mhz
Mainboard: Asus Prime B450 Plus

#### Results
| Effect Merging | FPS  |
|----------------|------|
| enabled           | ~345  |
| disabled          | ~260  |
