### ISSUE TITLE
Cannot read property 'blendFunction' of undefined

### ISSUE THREAD

**Issue by a-barbieri** [vanruesc/postprocessing#98]
### Expect behavior
I'd like to use ShaderPass with my custom shader.

### Actual behavior
Trying to setup a ShaderPass I get this error.
> Uncaught TypeError: Cannot read property 'blendFunction' of undefined

### Code

```javascript
  import * as POST from "processing";

  const uniforms = { 
    // my uniforms
  }
  const shaderSettings = {
    uniforms: {
      "tDiffuse": { value: null },
      ...uniforms
    },
    // get vertex and fragment from HTML script
    vertexShader: document.getElementById("vertexFilter").textContent,
    fragmentShader: document.getElementById("fragmentFilter").textContent,
  };

  const renderPass = new POST.RenderPass(scene, camera);
  const effectPass = new POST.EffectPass(camera, new POST.ShaderPass(shaderSettings));
  effectPass.renderToScreen = true;
  effectComposer = new POST.EffectComposer(renderer);
  effectComposer.addPass(renderPass);
  effectComposer.addPass(effectPass);
```

### Version
postprocessing: `^5.0.0`

**Comment by a-barbieri** [comment]
I managed to obtain what I wanted in a different way:

```javascript
// replace
const effectPass = new POST.EffectPass(
  camera, 
  new POST.ShaderPass(shaderSettings)
);
// with
const effectPass = new POST.EffectPass(
  camera, 
  new POST.Effect(
    "myShader", 
    shaderSettings.fragmentShader,
    { uniforms: shaderSettings.uniforms }
  )
);
```

And using the following structure as the base of my fragment.

```c++
  void mainImage(const in vec4 inputColor, const in vec2 uv, out vec4 outputColor) {
    vec3 red = vec3(1.0, 0.0, 0.0);
    outputColor = vec4(red, inputColor.a);
  }
```

**Comment by vanruesc** [comment]
Hi!

> Uncaught TypeError: Cannot read property 'blendFunction' of undefined

This error occurs because the `ShaderPass` is not an `Effect` and thus not compatible with the `EffectPass`.

> I managed to obtain what I wanted in a different way

The `ShaderPass` is the preferred choice if you just want to render a standalone fullscreen shader which doesn't conform to the `Effect` shader structure. The `EffectPass` is best suited for chaining fullscreen effects and introduces additional features such as effect blending which may not be necessary if you don't use more than one effect.

Here's an example of how to use the `ShaderPass`, just in case:

```js
import { ShaderMaterial, Uniform } from "three";
import { ShaderPass } from "postprocessing";

const shaderPass = new ShaderPass(new ShaderMaterial({
	defines: { "LABEL" : "value" },
	uniforms: { "parameter1": new Uniform(1.0), "parameter2": new Uniform(2) },
	fragmentShader: <string>,
	vertexShader: <string>
}));

composer.addPass(new RenderPass(scene, camera));
composer.addPass(shaderPass);
```

**Comment by a-barbieri** [comment]
Thank you @vanruesc!
I wonder now how can I achieve to update those uniforms in the `render` function (which is the one I use in the `requestAnimationFrame`).

Shall I do the following?
```javascript
render() {
  shaderPass.uniforms. parameter1 = new Uniform(1.0)
  composer.render(scene, camera);
}
```

**Comment by vanruesc** [comment]
You could do something like this:

```js
const shaderMaterial = new ShaderMaterial({
	uniforms: {
		"tDiffuse": new Uniform(null),
		"parameter1": new Uniform(0)
	},
	fragmentShader: <string>,
	vertexShader: <string>
});

const shaderPass = new ShaderPass(shaderMaterial , "tDiffuse");

(function render() {

	requestAnimationFrame(render);

	// If you have a reference to the shader material:
	shaderMaterial.uniforms.parameter1.value = Math.random();
	// If you only have a reference to the shader pass:
	shaderPass.getFullscreenMaterial().uniforms.parameter1.value = Math.random();

	composer.render(/* The composer expects a frame delta value! */);

}());
```

**Comment by a-barbieri** [comment]
I've updated my code and even though it's working, I cannot get `tDiffuse` to work as expected (which is what I have [here](https://codepen.io/a-barbieri/pen/mzYRKK?editors=1000)).

Is there anything different from the standard `ShaderPass` that I should be aware of?

**Comment by a-barbieri** [comment]
Sorry, I've just read better your code.
```javascript
const shaderPass = new ShaderPass(shaderMaterial , "tDiffuse");
```

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
