### ISSUE TITLE
GodRaysEffect skinning support

### ISSUE THREAD

**Issue by jpweeks** [vanruesc/postprocessing#99]
GodRaysEffect currently doesn't support masking skinned meshes. Enabling `skinning` on `renderPassMask.overrideMaterial` fixes the issue, but maybe there's a more efficient way?

**Comment by vanruesc** [comment]
Hi,

thanks for reporting this issue.

> Enabling skinning on renderPassMask.overrideMaterial fixes the issue

We'd also need to enable `morphTargets` then, but you're right that this isn't a very efficient solution. The `OutlinePass` has the same performance issues.

> maybe there's a more efficient way?

Yes, I think it should be possible to avoid the additional render pass by relying on the depth texture of the scene. I was planning on revising the `GodRaysEffect` next, but I'm not sure when I'll be able to start working on that. For now I'll enable `skinning` and `morphTargets` for the `GodRaysEffect`.

**Comment by vanruesc** [comment]
Added preliminary skinning and morph targets support to `GodRaysEffect` in `postprocessing@5.2.2`.

**Comment by vanruesc** [comment]
The scalability of the `GodRaysEffect` has been improved in `postprocessing@6.0.0`. The effect now uses depth textures to create a masked light scene and no longer re-renders the main scene.
